### ISSUE TITLE
UX: Greyed out copy button on recieve

### ISSUE THREAD

**Issue by My1** [digitalbitbox/bitbox-wallet-app#1001]
the recieve screen on the Bitboxapp shows a greyed out copy button in a grey text field which is entirely useless as (as far as it seems) there is no way it will ever be active, considering the address will only be shown in a new layer when you go verify.

couldnt this just be removed? as someone might easily try to intuitively click it just to realize they have to verify?

![image](https://user-images.githubusercontent.com/6696524/93331324-54964e80-f820-11ea-804f-48cd881f9304.png)

**Comment by micressor** [comment]
Same here.

### Device
OS: Linux
App Version: v4.26.0
Firmware: bitbox02 v9.4.0
