### ISSUE TITLE
docker image tag

### ISSUE THREAD

**Issue by NickeZ** [digitalbitbox/bitbox-wallet-app#1060]
Trying to run the app without rebuilding the docker image I did:

```
docker pull shiftcrypto/bitbox-wallet-app
```

Which did not fetch the latest because "latest" doesn't point to 6. So then I did:

```
docker pull shiftcrypto/bitbox-wallet-app:6
```

But then `make dockerdev` didn't work it complained that it couldn't find `bitbox-wallet`. So I had to

```
docker tag shiftcrypto/bitbox-wallet-app:6 bitbox-wallet
```

I think it should be easier to get started than this. `make dockerinit` and `make dockerdev` could use the same name that you use on docker hub. :)

I think the above instructions are correct because I managed to run the app.

**Comment by benma** [comment]
Good point. I pushed the :latest tag now and made this to unify the names: https://github.com/digitalbitbox/bitbox-wallet-app/pull/1064
