### ISSUE TITLE
support additional erc20 tokens

### ISSUE THREAD

**Issue by PalinuroSec** [digitalbitbox/bitbox-wallet-app#1075]
Hello, i would like my client to support a couple of additional erc20 tokens that i am interested in, and i would like to avoid MEW and other external clients for it.

Do you have any recommendation on how to modify the frontend to add such tokens.

I am doing it primarily for my personal needs, but it is also the perfect chance to get familiar with the code and eventually push you to consider adding new tokens or make it easy for users like me to add them autonomously (maybe through a config file instead of having them hardcoded?)

**Comment by benma** [comment]
Which tokens are those? Are they in the list starting here?

https://github.com/digitalbitbox/bitbox02-firmware/blob/b5e0004f35ed65f4606f23f87e80e464f2da77d5/src/apps/eth/eth_params.c#L63

To add it to the BitBoxApp, you'll need to extend these lists:

https://github.com/digitalbitbox/bitbox-wallet-app/blob/1345d59becd42057cfc30c336109ee452cffeea9/backend/erc20.go#L30

https://github.com/digitalbitbox/bitbox-wallet-app/blob/1345d59becd42057cfc30c336109ee452cffeea9/frontends/web/src/routes/settings/settings.tsx#L64

https://github.com/digitalbitbox/bitbox-wallet-app/blob/1345d59becd42057cfc30c336109ee452cffeea9/backend/rates/rates.go#L75

A config file sounds interesting.

**Comment by benma** [comment]
> can i open a pull request to have pax gold officially integrated? of course after fixing the icon and reverting the change to the firmware library.

Yeah, go ahead.

**Comment by PalinuroSec** [comment]
what happens if a token is not listed in eth_params.c or if its contract address has changed (i.e. lend to aave migration) ?

**Comment by benma** [comment]
When confirming a tx, the device shows the raw contract data for verification as a fallback, but of course that is not ergonomic to verify. If you have a specific token that you need that is not in the list, you can make a PR to add it, or open an issue for it.

**Comment by PalinuroSec** [comment]
i have deleted my old repo and re-added my tokens on top of the new codebase, since i saw new conflucting commits since my repo was forked

here the pull request
https://github.com/digitalbitbox/bitbox-wallet-app/pull/1077

**Comment by PalinuroSec** [comment]
tokens added, but even if they appear in the settings, they no longer appear in the coin list or in the summary. is it related to the recent updates?

FYI
in the version that worked  vendor/github.com/digitalbitbox/bitbox02-api-go/api/firmware/device.go was also mistakenly edited

**Comment by PalinuroSec** [comment]
just tried to edit  vendor/github.com/digitalbitbox/bitbox02-api-go/api/firmware/device.go again. paxg works, wbtc doesn't even if name, tag, decimals, and contract are the same of https://github.com/digitalbitbox/bitbox02-firmware/blob/b5e0004f35ed65f4606f23f87e80e464f2da77d5/src/apps/eth/eth_params.c#L63

**Comment by PalinuroSec** [comment]
merged. thanks for all the fish
