### ISSUE TITLE
electrs v0.8.6 requires electrum client protocol v1.4

### ISSUE THREAD

**Issue by wilya7** [digitalbitbox/bitbox-wallet-app#1123]
I had to update _electrs_ server to **v0.8.6** due to this [issue](https://github.com/romanz/electrs/issues/331) with _electrum_ 4.0.6 . Since the update, while _electrum_ happily works again, _bitbox-wallet_ does not work anymore. I believe the reason is stated in _electrs_ log:

`WARN - rpc #1 server.version [String("0.0.1"), String("1.2")] failed: Error: 0.0.1 requested protocol version 1.2, server supports 1.4`

This is the _electrs_ [commit](https://github.com/romanz/electrs/commit/b2b08ceaffcf47734c0db87aee8424d4afef0bdb) that introduced this behavior and this is the [issue](https://github.com/romanz/electrs/issues/314)  that requested its introduction.

Would be possible to support electrum client protocol **v1.4**?

This affects also [issue 449](https://github.com/digitalbitbox/bitbox-wallet-app/issues/499) as now it is not possible to use _electrs_ as recommended without installing _electrs_ < v0.8.6 which makes it impossible to install and use  _electrum_  as well.

Thanks.

**Comment by x1ddos** [comment]
> Would be possible to support electrum client protocol v1.4?

Absolutely. Working on it. The plan is for it to make it into the next app release.

**Comment by benma** [comment]
The fix is merged and compatibility is restored in the next release, which is going to be published very soon. Thanks for your patience.

**Comment by x1ddos** [comment]
FTR https://github.com/digitalbitbox/bitbox-wallet-app/releases/tag/v4.24.1 is where the compatibility is restored.
