### ISSUE TITLE
Adding Support for XinFin[XDC] Network Mainnet chain

### ISSUE THREAD

**Issue by hckhunk** [digitalbitbox/bitbox-wallet-app#1129]
**XinFin Network mainnet chain support**
How do we initiate support for XinFin[XDC] Network support? It is a DeFi + NFT protocol

**Added to Ethereum compatible chain list**
https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-50.json

**Comment by benma** [comment]
I am afraid we currently have no plans to add support for XinFin in the BitBoxApp. Best.
