### ISSUE TITLE
Wallet Signature Verification Issur

### ISSUE THREAD

**Issue by gazzagazza101** [digitalbitbox/bitbox-wallet-app#1131]
Hi,

Is this something to be worried about - WARNING in bold below. Followed the steps to verify the signature (non Tor) in Linux64 Other Distros).

gpg: assuming signed data in 'BitBox-4.24.1-x86_64.AppImage'
gpg: Signature made Sat 12 Dec 2020 14:57:25 GMT
gpg:                using RSA key 2D8876810AB092E451DCA894804538928C37EAE8
gpg: Good signature from "Marko Bencun <marko@shiftcrypto.ch>" [unknown]
gpg:                 aka "Marko Bencun <mbencun+pgp@gmail.com>" [unknown]
**gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 2260 E482 8888 2C76 AFAA  319D 67A2 B160 F74D B275
     Subkey fingerprint: 2D88 7681 0AB0 92E4 51DC  A894 8045 3892 8C37 EAE8**

Thanks,
Gaz.

**Comment by benma** [comment]
GPG is telling you that there is no chain of trust between you and me (as in, you didn't verify and sign my key). You can tell by the `[unknown]` marker:

>  (The [ultimate] could say [unknown] or something else depending on your trust level.)

(from https://github.com/digitalbitbox/bitbox-wallet-app/releases).

I confirm that `2260E48288882C76AFAA319D67A2B160F74DB275` is my primary key fingerprint. You can also verify this at keybase.io:

https://keybase.io/benma

Cheers.
