### ISSUE TITLE
Add XinFin-XDC Network support

### ISSUE THREAD

**Issue by AaditiGirkar** [digitalbitbox/bitbox-wallet-app#1133]
Hello Team,

Please have a look at the XinFin-network use cases, The XinFin blockchain utilizes the XinFin Delegated Proof-of-Stake consensus(XDPoS) mechanism for smoother digitization of industrial processes and almost-instant trade settlement.

Add XinFin-XDC Network support in Ellipal Wallet.

XinFin Network:- https://explorer.xinfin.network/home
XinPay Chrome Extension:- https://chrome.google.com/webstore/detail/xinpay/bocpokimicclpaiekenaeelehdjllofo
XDC Wallet (Android App):- https://play.google.com/store/apps/details?id=com.xdcwallet&hl=en&gl=US
Github:- https://github.com/XinFinOrg/XDPoSChain
Docker FullNode:- https://github.com/xinfinorg/XinFin-Node
Integration Code example: https://xinfin.org/exchange-listing-resource

Technical Community Support available at:

Telegram Community: https://t.me/XinFinDevelopers
Slack Community: https://xinfin-public.slack.com/messages/CELR2M831/
Slack Invitation Link: https://launchpass.com/xinfin-public
Technical help Resource: http://howto.xinfin.org/

Happy to talk commercials as well as ready to support with large XinFin Community members support to grow adoption with your team.

**Comment by benma** [comment]
This is not Ellipal ;) 

Duplicate of https://github.com/digitalbitbox/bitbox-wallet-app/issues/1129.
