### ISSUE TITLE
Feature Request: Option to define multiple Wallets of a currency

### ISSUE THREAD

**Issue by cstenglein** [digitalbitbox/bitbox-wallet-app#1167]
As a user I would like to create multiple wallets of a currency (e.g. 3 different bitcoin wallets, 2 ETH wallets, etc.).

In addition, I would like to define labels for it.

This would make it easier to manage multiple sources of the cryptos than coin control.

It could look something like this:

![multiple_accounts_example](https://user-images.githubusercontent.com/9399034/106358382-bd7bf000-6303-11eb-8de1-5461f9523b89.png)

**Comment by jadzeidan** [comment]
@cstenglein Thanks for the feature request, yes we definitely want to add multiple accounts and let you name them. Hard to say when this feature will be out but it is definitely planned. Will keep you updated!

**Comment by thisconnect** [comment]
Support for multiple unified accounts was added in `4.28.0`.
