### ISSUE TITLE
Add WalletConnect to mobile app

### ISSUE THREAD

**Issue by qwerty-emilie** [digitalbitbox/bitbox-wallet-app#1170]
Many dApps utilize WalletConnect (https://walletconnect.org/) to facilitate easy communication between Ethereum-powered distributed apps and wallets. Integrating this into the mobile app would allow bitbox02 users to use their hardware wallet with these apps in a convenient and safe way.

**Comment by benma** [comment]
Thanks. @jadzeidan can you check it out?

**Comment by thisconnect** [comment]
WalletConnect support was added in 4.40.0 https://github.com/digitalbitbox/bitbox-wallet-app/releases/tag/v4.40.0
