### ISSUE TITLE
GUI issue: hard to read mouseover box, in macOS (10.14.6 Mojave)

### ISSUE THREAD

**Issue by wilya7** [digitalbitbox/bitbox-wallet-app#1193]
In my macOS Mojave it is very hard to read the mouseover text, see enclosed picture.

Would it be possible to use more contrast between the background and the text stroke? 

![Screenshot 2021-02-28 at 07 05 26](https://user-images.githubusercontent.com/1757313/109409603-6dd92480-7994-11eb-9a4e-6da26f5a0f22.png)

**Comment by thisconnect** [comment]
@wilya7 Thanks for your feedback, it seems you use darkMode. I tested the BitBoxApp on Catalina and BigSur and it looks a bit better, still not perfect, but it seems that the currently bundled Qt webview is also a factor in this. 

This should improve on newer macOS and once we can upgrade the Qt (webview) version. Also we might completely move away from using native tooltips in the future, but this will happen when we make the general UI overhaul and then also add proper darktheme support.

Here are the screenshot on Catalina and Big Sur

macOS Catalina with dark theme enabled

![Screen Shot 2021-03-01 at 11 44 51 AM](https://user-images.githubusercontent.com/546900/109495883-2cc63a80-7a90-11eb-9751-8fa0233bf288.png)

compare to a tooltip in the chrome browser
![Screen Shot 2021-03-01 at 12 15 40 PM](https://user-images.githubusercontent.com/546900/109495886-2df76780-7a90-11eb-990d-77d5bfce6962.png)

macOS BigSur

![unnamed](https://user-images.githubusercontent.com/546900/109496109-80d11f00-7a90-11eb-831b-9bcbc2419958.png)

**Comment by thisconnect** [comment]
A custom build with newer Qt version on Catalina seems to be ok
![Screen Shot 2021-03-01 at 2 00 19 PM](https://user-images.githubusercontent.com/546900/109500468-95181a80-7a96-11eb-880d-069f43a7178f.png)

**Comment by wilya7** [comment]
@thisconnect 
Yes, I use dark mode. I can't test Catalina as I still use several 32 bit software, so I am stuck in Mojave. Thank you for taking care of the issue. It doesn't really affect me. I opened a bug report just to try to be minimally useful. Being a big fan of your product I try to help, even if just with a minor bug report.

**Comment by x1ddos** [comment]
> unfortunately we have to wait for Ubuntu LTS, but we will up the Qt version

Ubuntu 16.04 is scheduled for end of line on April 30, 2021: https://ubuntu.com/about/release-cycle
We can and should then upgrade Qt to 5.15: https://doc.qt.io/qt-5/supported-platforms.html

**Comment by thisconnect** [comment]
@wilya7 sorry for the long delay, in the meantime we have updated to a newer Qt version, unfortunately I don't have access to macOS Mojave. Could you test if the issue is still present?

**Comment by wilya7** [comment]
@thisconnect Thank you for fixing the bug. I really appreciate it. Now in my setting, Mojave dark mode, the strings are perfectly readable. As far as I am concerned we can close the bug.
