### ISSUE TITLE
Feature Request: Message signing support

### ISSUE THREAD

**Issue by dspicher** [digitalbitbox/bitbox-wallet-app#1230]
I'd like to be able to sign messages, along the lines of:

https://github.com/bitcoin/bitcoin/blob/master/src/util/message.cpp#L56

**Comment by benma** [comment]
For which purpose?

Fyi, one can sign using HWI (master) or Electrum already.

**Comment by x1ddos** [comment]
@dspicher do you mean signing a msg using the BitBoxApp UI?

**Comment by dspicher** [comment]
Yes, exactly.

**Comment by x1ddos** [comment]
+1 and we'll need it for AOPP as well.

**Comment by benma** [comment]
> +1 and we'll need it for AOPP as well.

That is different. In AOPP the message is already known, and the address is automatically chosen, so a generic message signing UI where you can choose the address and message is not needed.

@dspicher is this issue about AOPP or about message signing in general?

**Comment by x1ddos** [comment]
On 4/13/21 12:38 PM, benma wrote:
>> +1 and we'll need it for AOPP as well.
> 
> That is different. In AOPP the message is already known, and the address is automatically chosen, so a generic message signing UI where you can choose the address and message is not needed.

Sure it's different but from what I imagined we should be able to reuse 
a UI component and some code behind it. In fact, I think AOPP component 
could be easily based on top of the generic message signing.

> 
> @dspicher is this issue about AOPP or about message signing in general?
>

**Comment by benma** [comment]
> Sure it's different but from what I imagined we should be able to reuse a UI component and some code behind it. In fact, I think AOPP component could be easily based on top of the generic message signing.

It certainly could be, but wouldn't it be a lot easier and better UX to just show 'please confirm on the BitBox02' in the app when clicking an AOPP link, the user reads and signs on the BitBox02, and the process is done?

**Comment by lf94** [comment]
As someone who has dealt with a ton of signature based work in the past year, being able to sign within the wallet software is a necessity for verification cases, and some developers will not want to write any software around this.

I agree with @benma that typically just requesting a signature from the device directly is much preferred and a better experience. This is what we do at Bity for our signature step. If you have any more questions please ask :slightly_smiling_face:

**Comment by thisconnect** [comment]
AOPP support has made it into 4.29.0, arbitrary messages can be signed with the BitBox through Electrum or SparrowWallet, closing this until further info is provided.
