### ISSUE TITLE
Account Summary not updating

### ISSUE THREAD

**Issue by kerry-tarrant** [digitalbitbox/bitbox-wallet-app#1233]
The Account Summary page has been stuck on April 15th at midnight and above the graph the it has remained "updating data..." since. Rebooting my laptop has not fixed it.

**Comment by x1ddos** [comment]
Hi Kerry. It seems like CoinGecko had some kind of a blip again and 
started denying our requests - we're using CoinGecko for all exchange rates.

Please restart the app. I'm confident the issue should be resolved now.

Sorry for the troubles.

**Comment by x1ddos** [comment]
@kerry-tarrant can you confirm this is now working?

**Comment by kerry-tarrant** [comment]
@x1ddos Thanks for looking into this and fixing my issue! The problem has been resolved and the data is updating as expected.

**Comment by x1ddos** [comment]
Nice! :+1: 
We're also looking into making the app more resilient to cases like this in the future.
