### ISSUE TITLE
Account language

### ISSUE THREAD

**Issue by My1** [digitalbitbox/bitbox-wallet-app#1325]
This could be drastically improved as you dont "enable" and "disable" or "create"/"delete" accounts, but you just show/hide them.

**Comment by thisconnect** [comment]
Hey @My1, we currently plan to have activate/deactivate toggles for each account, not just for tokens but also for the coins.

Deactivating will reduce network traffic and hide the account from the sidebar, "My portfolio" and from the options under "Buy crypto".

What do you refer to by "this"? Also the title is "Account language" could you elaborate? (maybe we talk about something else?)

**Comment by My1** [comment]
"deactivating"/deleting or whatever most other wallets tend to use sounds more like that the account would be kinda unusable and all, which kinda isnt the case as you can for example still recieve on that account.

![image](https://user-images.githubusercontent.com/6696524/120886503-9c4b4900-c5ee-11eb-9c2f-1c333129d669.png)

![image](https://user-images.githubusercontent.com/6696524/120886509-abca9200-c5ee-11eb-9e5a-9a0b2dea18f7.png)

**Comment by thisconnect** [comment]
Option to hide accounts was added and "show/hide" wording is used, thanks for your input @My1  👍 

![Screen Shot 2021-09-14 at 3 57 19 PM](https://user-images.githubusercontent.com/546900/133271239-58af1f48-fe4c-4c5b-bf33-0e3fea501495.png)
