### ISSUE TITLE
App error

### ISSUE THREAD

**Issue by cpolaco** [digitalbitbox/bitbox-wallet-app#1327]
Error: panicked at 'keystore unlock failed', src failed... 

Error disapear and i couldnt get complete description

**Comment by cpolaco** [comment]
Error: panicked at `keystore unlock failed`, src/bitbox02-rust/src/workflow/unlock.rs:87:14`

**Comment by jstrnbrg** [comment]
@cpolaco  Does this happen repeatedly or just once? What were you trying to do on your BitBox02 when you saw that error? Which firmware version?

**Comment by cpolaco** [comment]
Im on the last firmware version, i cant open my wallet since the error started, both desktop and android, i connect bitbox02 open the app, the app give me error Genuine check failed then the panicked error appears at bitbox, just reinstalled both pc and desktop same problem, used pc and android older version app, same problem...

**Comment by jstrnbrg** [comment]
@cpolaco Thanks. Please contact support@shiftcrypto.ch and link to this issue so that my colleague knows about this github issue.

**Comment by cpolaco** [comment]
Ok thanks, my coins are safe?

**Comment by x1ddos** [comment]
> Ok thanks, my coins are safe?

@cpolaco yes, absolutely. the support will send you replacement but we'd really like to get this device to be able to reproduce the error and see how to fix it in the future. let's continue in the support ticket!
