### ISSUE TITLE
unhandled responses from etherscan?

### ISSUE THREAD

**Issue by pwntr** [digitalbitbox/bitbox-wallet-app#1344]
(Sorry in advance for the large images)

Just got my BotBox02 Multi set up, only to discover that the Ethereum portion of it seems a bit iffy (Burger Menu -> Accounts -> Ethereum). Sometimes, not always, I'm receiving the following errors. Possibly backend / etherscan.io related? Using the Linux and Android apps, both latest version, and firmware on BitBox02 @ v9.6.0 (latest). Bitcoin and Litecoin parts of the app seem not affected.

Thx for the help!

![error - linux wallet](https://user-images.githubusercontent.com/715243/122447111-b2b8b380-cfa3-11eb-97d7-775be9eb3a1d.png)
![Screenshot_20210617-192435](https://user-images.githubusercontent.com/715243/122447274-dc71da80-cfa3-11eb-9ffd-3f1564ecce4e.jpg)
![Screenshot_20210617-192346](https://user-images.githubusercontent.com/715243/122447275-dd0a7100-cfa3-11eb-93d7-937173115b6e.jpg)

**Comment by x1ddos** [comment]
Yeah, it's etherscan's rate limiting kicking in:
https://info.etherscan.com/api-return-errors/

We're considering setting up our own ETH nodes to get rid of etherscan and the rate limits.
