### ISSUE TITLE
Cancelled transaction listed as "pending"

### ISSUE THREAD

**Issue by feld** [digitalbitbox/bitbox-wallet-app#1376]
I have a transaction I sent which was cancelled but BitBox app permanently lists it as "pending" and it's pinned at the top of the transaction history. If you try to look up the transaction via the etherscan link it shows the TxnHash hash is not known.

**Comment by benma** [comment]
Which BitBoxApp version are you using? If it is not 4.28.2, please try upgrading first and seeing if this helps.

**Comment by thisconnect** [comment]
@feld does the issue still exist, have you tried a newer version?
