### ISSUE TITLE
Refactor electrum settings page to TypeScript

### ISSUE THREAD

**Issue by thisconnect** [digitalbitbox/bitbox-wallet-app#1492]
A few components are not rewritten to TypeScript usually BB01 related, but it would be great to have the electrum configuration in typescript.

https://github.com/digitalbitbox/bitbox-wallet-app/blob/master/frontends/web/src/routes/settings/electrum.jsx

**Comment by benma** [comment]
Done in https://github.com/digitalbitbox/bitbox-wallet-app/commit/95eddbde86524fbc1c058b0b9207e398c8615d7a
