### ISSUE TITLE
Long road to React

### ISSUE THREAD

**Issue by thisconnect** [digitalbitbox/bitbox-wallet-app#1499]
- Change class to className (can be done on `master`)
- React router (on `staging-react`)

**Comment by thisconnect** [comment]
PR is open https://github.com/digitalbitbox/bitbox-wallet-app/pull/1531

**Comment by benma** [comment]
New bug:

Opening the app with an unlocked device inserted now routes to "manage device" instead of "portfolio"

**Comment by thisconnect** [comment]
I'll have a look at the routing, but will first write a small manual test protocol.

> Opening the app with an unlocked device inserted now routes to "manage device" instead of "portfolio"

**Comment by thisconnect** [comment]
FYI this is not a new bug, it also happens with 4.30.0

**Comment by benma** [comment]
> FYI this is not a new bug, it also happens with 4.30.0

cursed bug, keeps coming back :O

**Comment by BrianCraig** [comment]
@thisconnect can we close this issue?

**Comment by thisconnect** [comment]
@BrianCraig I have a fix and will open a PR in a moment

> @thisconnect can we close this issue?

**Comment by thisconnect** [comment]
But yes lets close this issue and make new ones, closing if favor or 
- https://github.com/digitalbitbox/bitbox-wallet-app/issues/1546
