### ISSUE TITLE
Update banner in android app should link to the playstore

### ISSUE THREAD

**Issue by thisconnect** [digitalbitbox/bitbox-wallet-app#1533]
Currently update bbapp banner inapp goes to shiftcrypto.ch/download that is fine for desktop users, but unnecessary on Android as it should directly go to the Play Store
- https://play.google.com/store/apps/details?id=ch.shiftcrypto.bitboxapp&utm_source=website&pcampaignid=pcampaignidMKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1

**Comment by x1ddos** [comment]
what about independent APK installs? like the one we publish with each release on https://github.com/digitalbitbox/bitbox-wallet-app/releases

![image](https://user-images.githubusercontent.com/25405/147471764-5e9f38ab-e4f1-486b-b970-021d0f12dbfd.png)

also, what about f-droid? see https://github.com/digitalbitbox/bitbox-wallet-app/issues/1171

**Comment by benma** [comment]
We discussed offline that the vast majority of users use playstore or similar where the app auto updates or has update notifications, and we can simply hide the download button.
