### ISSUE TITLE
loading flicker

### ISSUE THREAD

**Issue by thisconnect** [digitalbitbox/bitbox-wallet-app#1542]
> the only thing i noticed that there is a whitescreen saying 'loading' for a splti second before the rest of the app loads.

**Comment by thisconnect** [comment]
The smallest change would be to just remove the string "loading".

Maybe this changes anyway after upgrade react-i18next https://github.com/digitalbitbox/bitbox-wallet-app/issues/1543

**Comment by BrianCraig** [comment]
`i18next` can't be provided syncronously because it gets the current language from the backend config
`https://github.com/digitalbitbox/bitbox-wallet-app/blob/449eb96c19b209ba1b86253a5abdea8b63651381/frontends/web/src/i18n/config.js#L32`

**Comment by thisconnect** [comment]
Thanks for looking into it. I'll close this, as the visual flicker is gone with https://github.com/digitalbitbox/bitbox-wallet-app/commit/2add713a5cf9beadca3fa1dc7a71602b459c6f95
