### ISSUE TITLE
Frontend: use `exactOptionalPropertyTypes: true` ts config

### ISSUE THREAD

**Issue by BrianCraig** [digitalbitbox/bitbox-wallet-app#1553]
https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes

**Comment by thisconnect** [comment]
we assign undefined in many places. I think we shouldn't use this rule. i.e. https://github.com/digitalbitbox/bitbox-wallet-app/pull/2456/files#diff-504497115e755a3814171cf73b608b4c2adce05949018bbeabfd9fe88403d0c9R57

**Comment by benma** [comment]
> we assign undefined in many places. I think we shouldn't use this rule. i.e. https://github.com/digitalbitbox/bitbox-wallet-app/pull/2456/files#diff-504497115e755a3814171cf73b608b4c2adce05949018bbeabfd9fe88403d0c9R57

I don't understand, what does this have to do with the link, and why is this rule not useful? Looks very useful to me not to be able to assign `undefined` to something that does not have `undefined` as an option in its type.

**Comment by thisconnect** [comment]
So far we don't care if the prop is absent or if it is `undefined`.

but that was a bad example 😇. I just assumed they typed Link component with `onClick?: (MouseEvent) => void`, but they explicitly allow `undefined`. 

![Screen Shot 2023-12-23 at 13 49 23](https://github.com/digitalbitbox/bitbox-wallet-app/assets/546900/769b196a-bb10-430b-9db8-5322354c867a)

IMO the rule is not useful, as we do not differentiate between uninitialized prop vs. `props={undefined}` in our codebase.

We use optional prop marked with question mark a lot, `prop?: TSometype` and also sometimes initialize with `undefined`. If we enable the rule we have to explicitly allow `undefined` .. i.e. `prop?: TSometype | undefined`.

here is one example if we enable the rule.

```
src/components/balance/balance.tsx:54:12 - error TS2375: Type '{ amount: IAmount; tableRow: true; noAction: boolean | undefined; noBtcZeroes: true; }' is not assignable to type 'TProvidedProps' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
  Types of property 'noAction' are incompatible.
    Type 'boolean | undefined' is not assignable to type 'boolean'.
      Type 'undefined' is not assignable to type 'boolean'.

54           <FiatConversion
              ~~~~~~~~~~~~~~
```

I currently don't see how it would help if we add or `undefined` to all optional props. 

This would be the fix:

```diff
diff --git a/frontends/web/src/components/rates/rates.tsx b/frontends/web/src/components/rates/rates.tsx
index 008a2a584..7816e1ac7 100644
--- a/frontends/web/src/components/rates/rates.tsx
+++ b/frontends/web/src/components/rates/rates.tsx
@@ -62,7 +62,7 @@ type TProvidedProps = {
     tableRow?: boolean;
     unstyled?: boolean;
     skipUnit?: boolean;
-    noAction?: boolean;
+    noAction?: boolean | undefined;
     sign?: string;
     noBtcZeroes?: boolean;
     alwaysShowAmounts?: boolean;
```

IMO the frontend should not behave differently if the prop is missing or if it is explicitly set to `undefined`. I would find that weird to be honest.

**Comment by thisconnect** [comment]
I'm not 100% sure. please let me know if we should look into this. feel free to reopen.

**Comment by benma** [comment]
I have not ran into any issues, so I don't care much either way. Slight preference to keep it be true to the actual semantics of TypeScript (if that makes sense :shrug: )
