### ISSUE TITLE
Qt app: Uncaught ReferenceError: globalThis is not defined at 046c0b8f

### ISSUE THREAD

**Issue by x1ddos** [digitalbitbox/bitbox-wallet-app#1560]
running a build off of latest master, i get a blank app screen and this error on the console:

```
$ ./frontends/qt/build/BitBoxApp-046c0b8f-x86_64.AppImage
Sandboxing disabled by user.
Loading log config from '.config/bitbox/logging.json'.
Logging into '.config/bitbox/log.txt' from 'debug'.
js: Uncaught ReferenceError: globalThis is not defined
```

not the first time... how can we make these regression bugs appear less frequent?

/cc @thisconnect @BrianCraig

**Comment by x1ddos** [comment]
running git bisect to pin-point the commit causing this fails at some point at 5b718231 with:

```
> react-scripts build

Creating an optimized production build...
Failed to compile.

SyntaxError: unknown: Namespace tags are not supported by default. React's JSX doesn't support namespace tags. You can set `throwI
fNamespace: false` to bypass this warning.
   6 |   ...props
   7 | }, svgRef) {
>  8 |   return <svg xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:cc="http://creativecommons.org/ns#" xmlns:rdf="http://www.w
3.org/1999/02/22-rdf-syntax-ns#" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" height={32} width={32.0
00004} id="svg4" viewBox="0 0 32.000004 32.000001" ref={svgRef} aria-labelledby={titleId} {...props}>{title ? <title id={titleId}>
{title}</title> : null}<metadata id="metadata10"><rdf:RDF><cc:Work rdf:about=""><dc:format>{"image/svg+xml"}</dc:format><dc:type r
df:resource="http://purl.org/dc/dcmitype/StillImage" /><dc:title /></cc:Work></rdf:RDF></metadata><defs id="defs8" /><g style={{
     |               ^^^^^^^^
   9 |       fill: "#bfbbbb",
```

this is one of the reasons why **every** commit merged into master must build. lots of pain and wasted time otherwise.

**Comment by x1ddos** [comment]
> reasons why every commit merged into master must build

if one doesn't build, worst case is squash it with something that builds

**Comment by x1ddos** [comment]
it looks like something happened around https://github.com/digitalbitbox/bitbox-wallet-app/pull/1528 but can't bisect due to unbuildable commits:

```
$ git bisect bad
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
5b718231a47c50060594ebb1c3e3f65d814934c1
87f87f3a6e454ef4e4eb122271fcc1e72c469517
6a7d5db395bf1dc25bec5e64a6454463e2ea4dee
We cannot bisect more!
```

![image](https://user-images.githubusercontent.com/25405/147476084-cc9c1f22-ef8c-45cc-aec0-acbaf18e4202.png)

**Comment by thisconnect** [comment]
@x1ddos with which nodejs version did you build?

apparently there is a https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#browser_compatibility ... never seen this one tbh

**Comment by x1ddos** [comment]
:shamecube: i was still building with qt5.12 and it actually works with qt5.15 - no blank screen. very sorry for the noise. although, trying to make every commit buildable is a good thing either way.

**Comment by thisconnect** [comment]
> very sorry for the noise. although, trying to make every commit buildable is a good thing either way.

don't worry @x1ddos and yes 100% agree with every commit buildable, sorry didn't make it in react migration, but I'll try in the future 👍
