### ISSUE TITLE
Add NOK as fiat currency

### ISSUE THREAD

**Issue by schjonhaug** [digitalbitbox/bitbox-wallet-app#1564]
Would you be willing to add support for Norwegian krone (NOK) as fiat currency? If so, I could make a PR.

**Comment by x1ddos** [comment]
NOK is repoter as supported at https://api.coingecko.com/api/v3/simple/supported_vs_currencies - coingecko is what we use for exchange rates. so, i don't see why not!

**Comment by schjonhaug** [comment]
Thanks, made a draft PR at https://github.com/digitalbitbox/bitbox-wallet-app/pull/1566 because I have some questions.
