### ISSUE TITLE
Show "update available" notification on Android when installed from APK

### ISSUE THREAD

**Issue by x1ddos** [digitalbitbox/bitbox-wallet-app#1579]
The update banner is now hidden since https://github.com/digitalbitbox/bitbox-wallet-app/pull/1570 so users who install the app manually from APK won't be notified anymore. Although we don't know exactly the ratio of manual APK install vs playstore, the assumption is that manual installs are much fewer.

Acoording to [github release asset downloads count](https://api.github.com/repos/digitalbitbox/bitbox-wallet-app/releases), last 3 releases the APK was downloaded 40, 10 and and 28 times. Play store shows over 5k installs/upgrades for the latest release:

![image](https://user-images.githubusercontent.com/25405/148747889-ebe19190-32b5-4eaa-ae39-d968fcaf1427.png)

Once https://github.com/digitalbitbox/bitbox-wallet-app/issues/1171 is done, f-droid users will be in the same category as playstore - auto upgrades from f-droid source.

Nevertheless, we should not drop this completely and reinstate the banner one day.

**Comment by benma** [comment]
> The update banner is now hidden since #1570

Actually the banner is still shown, but the download button is hidden. @BrianCraig implemented it like this and I figured it was a good idea.

**Comment by x1ddos** [comment]
oh! that's a good compromise. i should've actually read that PR.
then i think there's nothing to do here.
