### ISSUE TITLE
Add SEK as Fiat currency 

### ISSUE THREAD

**Issue by lazerleif** [digitalbitbox/bitbox-wallet-app#1600]
Would you be willing to add support for Swedish krona (SEK) as fiat currency? 

SEK is repoted as supported at https://api.coingecko.com/api/v3/simple/supported_vs_currencies

**Comment by x1ddos** [comment]
of course. i guess exactly the same procedure as in https://github.com/digitalbitbox/bitbox-wallet-app/pull/1566

thanks!

**Comment by thisconnect** [comment]
@lazerleif do you want to make a PR?

**Comment by lazerleif** [comment]
Sure, i don't really know how thou, im a bit of a GitHub noob 😄
