### ISSUE TITLE
My portfolio: Show total bitcoin balance as well

### ISSUE THREAD

**Issue by cstenglein** [digitalbitbox/bitbox-wallet-app#1604]
Currently the "My portfolio" view just displays the different accounts and their balance in addition to the total balance in fiat:

![image](https://user-images.githubusercontent.com/9399034/150673236-1557ebe6-ba4d-47b7-b5dd-098c3ac14df4.png)

As a user, I would like to see the total bitcoin balance of the accounts as well.

**Comment by benma** [comment]
Work on this has started here: https://github.com/digitalbitbox/bitbox-wallet-app/pull/1487

**Comment by benma** [comment]
Completed in https://github.com/digitalbitbox/bitbox-wallet-app/pull/1620
