### ISSUE TITLE
check connection to own full works only once

### ISSUE THREAD

**Issue by micressor** [digitalbitbox/bitbox-wallet-app#1631]
Steps to reproduce:
1. Click on check (Überprüfen) button
2. Click ok after success message
3. Click one more to check button

After that it's hanging.
I guess because bitbox app does not notice that it is already connected.
It should be possible to test the connection several times.
Or the button should be grayed out with the message, "already connected".
![grafik](https://user-images.githubusercontent.com/131317/153821826-b39ddef7-f64c-4cd6-8387-63d9cbb31114.png)

**Comment by Stadicus** [comment]
If you're using a TLS connection, you first need to download the certificate. After that, it should be possible to check the connection again as many times as you want.

If you skip the "Download remote certificate", then the connection times out as it can't communicate. I agree that the error message there could be improved.

**Comment by benma** [comment]
@Stadicus if you can't connect initially, you can't even add the server (adding server is only possible after checking the connection once).

@micressor what electrum server and version are you using? does the same behaviour happen with the default nodes?

**Comment by micressor** [comment]
@benma It happens with EPS (electrum-personal-server) v0.2.2. With shiftcrypto's default nodes it does not happen.
But there is an important difference. EPS allows only one connection at a time.

**Comment by benma** [comment]
Can you try again with the latest app @micressor ?

**Comment by micressor** [comment]
@benma : I changed from EPS to an electrs instance. It here it works with App Version: 4.37.0.
