### ISSUE TITLE
Feature Request: Insert the possibility to COPY the txid

### ISSUE THREAD

**Issue by GerdOpp** [digitalbitbox/bitbox-wallet-app#1640]
For privacy reasons, it is not convenient to display the transaction id only as a LINK to an external blockchain explorer in the Transaction Details window. 

It would be nice to insert the possibility to COPY the txid, as is already the case with the btc address.

**Comment by benma** [comment]
@thisconnect i didn't see you assigned yourself :innocent: 

I quickly whipped up this: 

https://github.com/digitalbitbox/bitbox-wallet-app/pull/1642

Feel free to close or adapt or approve, not sure if the approach is good.

**Comment by benma** [comment]
We could also add a confirm prompt "Open link in default browser? <...>".

**Comment by benma** [comment]
The PR is merged. Thanks @GerdOpp - this will be available in the next release.
