### ISSUE TITLE
USB not recognized

### ISSUE THREAD

**Issue by akovia** [digitalbitbox/bitbox-wallet-app#1712]
Arch Linux
BitBox02 Multi-Coin

The hardware displays upon insertion
`BitBox02`
`Multi edition`
`BOOTLOADER`

I followed the guide [here](https://shiftcrypto.support/help/en-us/9-troubleshooting/15-usb-connection-issues-my-bitbox02-is-not-detected) for Linux, but the commands just hang and never complete.

Device is not shown in `lsusb` results
I am in the plugdev group.

Please help.

**Comment by benma** [comment]
Did you add the udev rules, and then also reboot after?

Are you using a cable or an adapter? If so, try without to see if it might be a faulty adapter/cable.

**Comment by akovia** [comment]
I tried adding the rules but it just hangs as I stated before.

I am currently trying to create these files by deciphering the commandline code, but I'm not very certain. It would be helpful if you could just post these files (or text) so I can place them manually.

**Comment by akovia** [comment]
Looks like I was able to create the udev rules manually. I don't write udev rules and didn't want to research the syntax, but it appears just removing the escapes and ensuring the new lines did the trick.

No idea why the commands wouldn't complete on my system, but they would just hang. Will close this once I have my wallet set up, but wanted to post my progress.

**Comment by benma** [comment]
Thanks.

Here are the files should you need them.

[rules.d.zip](https://github.com/digitalbitbox/bitbox-wallet-app/files/8886103/rules.d.zip)

**Comment by akovia** [comment]
Everything seems to work perfectly after overcoming that stumbling block.

Thank you very much for the very fast support. It reassuring.

Cheers!
