### ISSUE TITLE
Feature request: Automatically search and detect used/active accounts

### ISSUE THREAD

**Issue by sutterseba** [digitalbitbox/bitbox-wallet-app#1715]
Hi,

I see many users confused about their accounts not appearing when using a different device or after reinstalling the BitBox App.

This is not an issue if you know that simply adding accounts will derive the missing accounts again and everything is back to how it should be, but all of this confusion can be avoided by subsequently checking for used accounts until n accounts have been derived without active adresses, similarly to how adresses themselves are derived.

**Comment by benma** [comment]
:+1: That is certainly highly desirable and we will get this fixed at some point hopefully not too far in the future.

**Comment by benma** [comment]
This issue will be fixed for BTC/LTC with https://github.com/digitalbitbox/bitbox-wallet-app/pull/2086 in the next release.

**Comment by NicolaLS** [comment]
closed by [v.4.38.0](https://github.com/digitalbitbox/bitbox-wallet-app/releases/tag/v4.38.0) right ? @benma

**Comment by benma** [comment]
@NicolaLS right, for BTC/LTC accounts. ETH accounts are not scanned yet. Maybe best to open another issue for that.
