### ISSUE TITLE
Public Key error

### ISSUE THREAD

**Issue by herbyak** [digitalbitbox/bitbox-wallet-app#1719]
Hi,
when I try to get a public key with the mentioned fingerprint, the following error is displayed
![error message](https://user-images.githubusercontent.com/73648435/176851807-49a1da75-a6e2-426b-8519-0f3f5026a7c8.jpg)
Any suggestion what to do?:

**Comment by benma** [comment]
Looks like a local gpg problem. What does it say when you use `curl 'https://keys.openpgp.org/vks/v1/by-fingerprint/DD09E41309750EBFAE0DEF63509249B068D215AE' | gpg -v --import` (verbose output)

**Comment by herbyak** [comment]
the proper fingerprint is imported:
DD09E41309750EBFAE0DEF63509249B068D215AE.asc
If I try to import that key in gpg keychain the following error message is displayed.
![error message](https://user-images.githubusercontent.com/73648435/177007555-65c4c4fb-1b68-48d0-948b-355458dd5820.jpg)

**Comment by benma** [comment]
Maybe your permissions in they keyring folder are messed up somehow? Maybe parts of `~/.gnupg` are owned by root instead of your user? 

If you don't have anything important in there, you could also remove/move that folder: `sudo mv ~/.gnupg ~/.gnupk-old` and seeing if it works after that.

**Comment by herbyak** [comment]
You are right; I deleted the proposed folder and reinstalled everything. Now, it's working correctly.
Thxs a lot for your help 👍

**Comment by benma** [comment]
Great!
