### ISSUE TITLE
Question: Use Ethereum Wallet with Rabby on Polygon or Optimism?

### ISSUE THREAD

**Issue by pax85** [digitalbitbox/bitbox-wallet-app#1720]
Hi,

Quick question, since L2 solutions are still new to me.
Can I use a BitBox02 ethereum account via Rabby on the Polygon or Optimism network?

**Comment by benma** [comment]
Yeah, that should work.

**Comment by pax85** [comment]
Can confirm that at least Polygon worked fine.
