### ISSUE TITLE
frontent: allow setting a custom block explorer URL

### ISSUE THREAD

**Issue by mdcmeridius** [digitalbitbox/bitbox-wallet-app#1774]
Privacy is never too much.
In order to avoid doxxing yourself by using third-party block explorers, BitBox App should allow you to configure the block explorer URL (e.g.: a custom block explorer running in Raspibolt).

**Comment by thisconnect** [comment]
Also reported in https://github.com/digitalbitbox/bitbox-wallet-app/issues/1207

@mdcmeridius would you like to open a PR?

**Comment by mdcmeridius** [comment]
Sneak preview:

![image](https://user-images.githubusercontent.com/114249714/192098026-d9be830a-661d-4247-b0ac-622dc75f3c7b.png)
![image](https://user-images.githubusercontent.com/114249714/192098043-b786bfa9-dedf-44a8-ae82-a5709670f13a.png)

**Comment by mdcmeridius** [comment]
Should I add a button to bypass Tor proxy when connecting to a custom block explorer, or leave it hard-coded?

**Comment by benma** [comment]
> Should I add a button to bypass Tor proxy when connecting to a custom block explorer, or leave it hard-coded?

What do you mean exactly? Block explorer links are opened in the system browser.

**Comment by benma** [comment]
Sneak preview looks great :+1:  there are block explorer links also for testnet and altcoins. Not sure what to do with those. Maybe just label it 'Custom Bitcoin block explorer'?

**Comment by mdcmeridius** [comment]
Considering the following code:
```
		coin = btc.NewCoin(coinpkg.CodeBTC, "Bitcoin", "BTC", &chaincfg.MainNetParams, dbFolder, servers,
			"https://blockstream.info/tx/", backend.socksProxy)
```

I'm not sure whether the app will use the Tor Proxy (if defined) for these links.

(BTW, I agree with your labeling proposal)

**Comment by mdcmeridius** [comment]
More previews of when custom Bitcoin block explorer is enabled.

Before clicking:

![bitbox-custom-block-explorer](https://user-images.githubusercontent.com/114249714/192658117-c251f240-37ad-41ea-af10-3e46cfefc38c.png)

After clicking:

![bitbox-custom-block-explorer chrome](https://user-images.githubusercontent.com/114249714/192658121-a9fa33fe-3bb5-4dbf-aedf-87ab4769bf7a.png)

**Comment by schmitmd** [comment]
So I guess this is a "rejected" feature..?

**Comment by thisconnect** [comment]
@schmitmd no it is not rejected. It's just a duplicate issue see https://github.com/digitalbitbox/bitbox-wallet-app/issues/1207

**Comment by schmitmd** [comment]
Missed the tag. My apologies
