### ISSUE TITLE
Which platforms are supported?

### ISSUE THREAD

**Issue by jvaltin** [digitalbitbox/bitbox-wallet-app#19]
When supporting and testing builds of this repository, what platforms are supported? Which are expected to be functional and which are tested?

- Windows - which versions?
- Mac OS X - which versions?
- Debian Stretch ( QT 5.7.1 )
- Debian Buster ( QT 5.11.x )
- Fedora 28 ( QT 5.10.x )
- Fedora 29 ( QT 5.11.1 )
- Ubuntu 14.04 ( QT 5.2.1 )
- Ubuntu 16.04 ( QT 5.5.1 )
- Ubuntu 17.10 ( QT 5.9.1 ) 
- Ubuntu 18.04 ( QT 5.9.5 )

**Comment by benma** [comment]
The latest release supports Ubuntu 14.04 and later, an unknown number of Fedora versions, Win7/10, macOS 10.13+ (lower versions might also work). All 64 bit.

The Qt version used in each is the same (currently `5.8.0`, could probably be bumped), as the libraries, at the moment, are shipped with the application.

**Comment by jvaltin** [comment]
Would it be reasonable to target standalone releases with the latest QT 5.11.x?

**Comment by benma** [comment]
Yes, provided it runs on the supported platforms (Ubuntu 14.04 can be dropped if it matters).

**Comment by jvaltin** [comment]
Fedora 26, 27, and 28 should be explicitly tested and supported. Fedora 29 is a release scheduled for the near future and will need to be supported soon. We should consider testing before it is released.

**Comment by jvaltin** [comment]
> Supported for what, compiling/building from source or using a pre-built binary/package like AppImage?

We produce .deb and .rpm files, though we don't explicitly and specifically express to users where we expect those packages to function. I would like to see an explicit set of platforms where we expect the software to run, and where as developers, we're expected to ensure it works before a release. The question about builds is approximately the same - how should a new developer expect to be developing, testing, and building the software?

**Comment by jvaltin** [comment]
I think it makes sense to document this in a `BUILD.md` file. I'll push a simple document shortly.

**Comment by ferdzbautistaolazo** [comment]
Thanks,for the reminder.
