### ISSUE TITLE
How to hide amounts on apps?

### ISSUE THREAD

**Issue by satoshinotdead** [digitalbitbox/bitbox-wallet-app#2003]
Maybe I'm missing something but I didn't found that basic but crucial security feature.

**Comment by benma** [comment]
This feature indeed does not exist in the BitBoxApp. 

@jadzeidan Maybe something to consider adding along with watch-only functionality?

**Comment by jadzeidan** [comment]
Yeah sure it's a nice feature we can add. But not sure how it is related to watch-only. It can be added independently.

**Comment by benma** [comment]
This feature has been released in v4.40.0. See https://bitbox.swiss/blog/bitbox-12-2023-sustli-update/.
