### ISSUE TITLE
[Feature request] Include Monero ASAP

### ISSUE THREAD

**Issue by satoshinotdead** [digitalbitbox/bitbox-wallet-app#2005]
[Monero is growing adoption very fas](https://moneroj.net/percentage/)t. It's the only project that keeps their ethos fully focused on decentralization and I really don't understand how Bitbox (truly open-source) don't want to support.

May I know if there are plans or I will need to use my Trezor T that support the most secure and private cryptocurrency on the world?

**Comment by benma** [comment]
Hi. There are currently no plans to add Monero. I'll close this issue in favor of [this issue](https://github.com/digitalbitbox/bitbox02-firmware/issues/910) which also contains a request for Monero.
