### ISSUE TITLE
ios support

### ISSUE THREAD

**Issue by keon** [digitalbitbox/bitbox-wallet-app#2007]
I'd love to use my iphone with bitbox. 
I can contribute a bit if needed.

**Comment by benma** [comment]
Unfortunately iPhone support is not possible as Apple does not allow third party USB devices.

**Comment by keon** [comment]
@benma could you explain a bit more?
I'm not sure what the difference between Ledger vs BitBox USB

**Comment by benma** [comment]
Ledger uses Bluetooth to connect to the iPhone, not USB. The BitBox does not have Bluetooth.
