### ISSUE TITLE
.asc filename doesn't match file

### ISSUE THREAD

**Issue by akovia** [digitalbitbox/bitbox-wallet-app#2038]
Very deceiving and took me a while to figure out. 

You show the file and the asc both with the word `Appimage` capitalized in the files list, but it actually downloads the main file in lower case. This of course makes gpg verification fail.

https://i.ibb.co/Jvz7rKR/Bitbox-asc-gpg.jpg

**Comment by benma** [comment]
Hi @akovia 

I cannot reproduce this problem. The link for the AppImage download at https://github.com/digitalbitbox/bitbox-wallet-app/releases points to https://github.com/digitalbitbox/bitbox-wallet-app/releases/download/v4.36.0/BitBox-4.36.0-x86_64.AppImage, and when I download it, I get the right capitalization ("AppImage"). 

Which browser and OS do you use?

**Comment by akovia** [comment]
Hi @benma,
I use Brave browser on Linux. Not sure what to tell you, but the screenshot says it all.

Doesn't make sense to me that one browser could download a file with a different filename than another. You can see in the screenshot that I actually downloaded it twice because I thought maybe the first download was corrupted when I couldn't get a successful gpg verification. After changing the filename of the appimage to match the asc, it verified without issue.

I'm at work now using the same browser, but on a Windows machine instead of Linux. If I download it here, "Appimage" is indeed capitalized properly, which would mean the browser isn't a factor. I don't have a Linux machine here at work to test, but will try again when I get home and report back.

**Comment by akovia** [comment]
So after some playing around, it seems it's a KDE thing. There's an option in the file chooser to `Automatically select filename extension`, and apparently it will rename the extension to a predetermined format? All I know is that if I try to download the file after disabling that option, it will download as advertised. 

I've used XFCE for 15 yeas and just recently moved to KDE and it's been full of regrets. Sorry for the confusion, but maybe this might help someone else in the future. Glad it wasn't anything more than a setting.

Cheers

https://i.ibb.co/P6R4NRT/Bitbox-asc-gpg2.jpg

**Comment by benma** [comment]
Thanks for researching the problem. 

> I've used XFCE for 15 yeas and just recently moved to KDE and it's been full of regrets. 

If I may ask, what made you change to KDE?

**Comment by akovia** [comment]
> If I may ask, what made you change to KDE?
Sure

It was constant issues with accessing my NFS NAS. (among some smaller annoying issues) Slow or no access at times with gvfs. I finally got so fed up that after a quick test, I found that KDE worked properly with NFS so I took the plunge.

I now have a huge list of issues piled up with KDE and might just move back when I have the time. 

`"Grass is greener" `
I shoulda known better. It's pretty, has modern OS features not available in XFCE, but I'm finding it's not worth the price. This issue is the perfect example of an OS trying to think for you, and it tripped me up.

This is my current, shorthand list of issues.

- [ ] Windows reopening when opening settings
- [ ] Missing Recent Files in File Chooser
- [ ] Black screen in settings after awakening
- [ ] Luks saves p/w (No option to NOT)
- [ ] Can't pin some programs to taskbar 
- [ ] Some downloaded files (.torrent, .desktop) get opened by dolphin
- [ ] Blinking/flickering windows
- [ ] Some programs missing from task pager (alt-tab) [QBitorrent]
- [ ] Some windows open UNDER (TMM)
- [ ] Screenshots with mouse hover
- [ ] Typeahead
- [ ] Modifies file extensions when downloading

**Comment by benma** [comment]
Interesting, thanks for sharing! 

I am not familiar with NFS - is the KDE NFS tied to KDE? One would think these are packages/libraries that do not depend on the desktop env :shrug:
