### ISSUE TITLE
ETH Konten werden nicht angezeigt

### ISSUE THREAD

**Issue by murelli146** [digitalbitbox/bitbox-wallet-app#2128]
Konto 1 von Ledger wird auf der Bitbox richtig angezeigt.
Konto 2 bleibt das Konto ohne Guthaben auf 0

Vermutlich liegt es an der Keypath bei Bitbox:
Ledger Konto 1 „44’/60’/0’/0/0“ Bitbox Konto 1 „m/44’/60’/0’/0/0“
Ledger Konto 2 „44’/60’/1’/0/0“ Bitbox Konto 2 „m/44’/60’/0’/0/1“

**Comment by benma** [comment]
Hi

Das ist das gleiche Issue wie https://github.com/digitalbitbox/bitbox-wallet-app/issues/2125. Ich schliesse dieses damit alle Infos an einem Ort sind.
