### ISSUE TITLE
Feature request: Read-only mode / bitbox02 not connected

### ISSUE THREAD

**Issue by micressor** [digitalbitbox/bitbox-wallet-app#2162]
I miss the possibility to start the BitBox app in a read-only mode without the BitBox02 being connected.

Everything except signing transactions should be possible.

On desktop and mobile.

**Comment by benma** [comment]
This is a heavily requested feature and we will definitely look into this and keep this issue updated.

**Comment by benma** [comment]
This feature has been released in v4.40.0. See https://bitbox.swiss/blog/bitbox-12-2023-sustli-update/.
