### ISSUE TITLE
Feature Request: Sign/Verify Message

### ISSUE THREAD

**Issue by micressor** [digitalbitbox/bitbox-wallet-app#2164]
I miss the possibility to sign/verify messages "manually". Electrum example:
![grafik](https://github.com/digitalbitbox/bitbox-wallet-app/assets/131317/812e18d6-ced5-47a9-bf1d-893df9401551)

**Comment by benma** [comment]
Can you elaborate on the use case? Really the only uses we've seen are related to registering an address with a DCA service like Pocket or Relai. This is solved by AOPP. Other use cases ideally have their own workflows that address the use case directly.

Generic message signing is possible via third party wallets like Electrum. We don't plan on adding it to the BitBoxApp for the above reasons.
