### ISSUE TITLE
Bug: Stuck at unlock for devices with old firmware

### ISSUE THREAD

**Issue by cstenglein** [digitalbitbox/bitbox-wallet-app#2192]
I got two old Bitbox02 devices laying around: a multi and a btc-only one.

Both can not be unlocked with the current app release. The devices say "See the BitBox App" while the App says "Unlock" and the Unlock sequence doesn't trigger.

The btc-only one had firmware 9.8.0 on it, which I managed to update to 9.11.0 with an older app version (9.11.0 now works with the current app).

The multi one didn't work with the older app version (4.33.0) so I tried 4.30.0 which also didn't work. Releases prior to 4.30.0 only show a white screen.

OS: Ubuntu 23.04

**Comment by benma** [comment]
I just tested v9.8.0 on BitBoxApp 4.38.0 on Ubuntu and it unlocks and upgrades fine :thinking: Since v9.8 and the current version, nothing notable changed related to the unlock process too, so it would be unexpected that it behaved differently in that step.

What version is the multi?

**Comment by cstenglein** [comment]
Attached you can find the logs. I replaced the deviceId with DEVICE_ID.

[debug_log_bitbox.txt](https://github.com/digitalbitbox/bitbox-wallet-app/files/11958204/debug_log_bitbox.txt)

Looks like it's 9.6.0 for the multi edition and the attestation throws an error.

**Comment by laOtraNBA** [comment]
I have a similar problem...I can unlock the device but after a couple of seconds, the device says "See the BitBox App" again and I can't do anything. I have noticed that if i wait some seconds, I can introduce the pin again and its works well. 

Tested in BB02 firmware version 9.14.1 and BitboxApp version 4.38.0 over Windows.

**Comment by benma** [comment]
@laOtraNBA that sounds like a different issue altogether. What OS are you on?

**Comment by benma** [comment]
@laOtraNBA do you have Citrix installed by any chance? We've had reports of Citrix interfering. Otherwise please send your [log.txt](https://shiftcrypto.support/help/en-us/15-other/101-support-files) and a detailed description of the issue(s) to support@bitbox.swiss. Thanks.

**Comment by laOtraNBA** [comment]
> @laOtraNBA do you have Citrix installed by any chance? We've had reports of Citrix interfering. Otherwise please send your [log.txt](https://shiftcrypto.support/help/en-us/15-other/101-support-files) and a detailed description of the issue(s) to [support@bitbox.swiss](mailto:support@bitbox.swiss). Thanks.

Sorry for the delay. I don't even know what is Citrix xD. I will send the log file to you, thanks.

**Comment by benma** [comment]
@laOtraNBA indeed you can only have one app connected to the BitBox02 at once. Windows unfortunately does not allow opening a connection with exclusive access, unlike macOS and Linux.

**Comment by benma** [comment]
@cstenglein your log file says 'unknown error' :see_no_evil: does it happen repeatedly? Could the adapter/cable be defective? Try another USB port.

**Comment by cstenglein** [comment]
@benma I tried to use the BitBox directly on the Laptop, now it worked!

Looks like it's not the cable or the bitbox, but only one of my USB-C ports. If I use the other, it works. 

Kinda weird, since it works with the other BitBoxes (always using the same port for that).

Thank you very much, closing the issue :)
