### ISSUE TITLE
Welcome screen msg SD warning/DCA  is in two languages.

### ISSUE THREAD

**Issue by TLausZ** [digitalbitbox/bitbox-wallet-app#2437]
Set up new Bitbox on Win11 (with German locale?) The warning msg and the DCA notification had two different languages. See screenshot.
![image](https://github.com/digitalbitbox/bitbox-wallet-app/assets/9079817/182e4d3f-0401-4272-85b1-db2dbb4ef23c)

**Comment by thisconnect** [comment]
I believe this was caused due to locale with country info i.e. `de-ch` or similar. This should be fixed with the next release. Related: https://github.com/digitalbitbox/bitbox-wallet-app/commit/bf70be385f422537b896ce6c853d425ee48f8f1e

**Comment by thisconnect** [comment]
@TLausZ can you check with v4.40.0 https://github.com/digitalbitbox/bitbox-wallet-app/releases/tag/v4.40.0 ?

**Comment by TLausZ** [comment]
solved with v4.40.0

**Comment by thisconnect** [comment]
@TLausZ thanks for confirming.
