### ISSUE TITLE
AppImage missing icons file

### ISSUE THREAD

**Issue by mercurytoxic** [digitalbitbox/bitbox-wallet-app#25]
To package BitBox wallet app for Arch Linux AUR from the .AppImage, I extract the bitbox.desktop and bitbox(.png, .svg, etc) to include them in the current desktop environment. But the .AppImage does not include any image files.

`$ ./BitBox-4.1.0-x86_64.AppImage --appimage-extract`
`$ ls -la`
`drwx------  8 pizzaman users     4096 Aug 21 14:20 .`
`drwxr-xr-x  5 pizzaman users     4096 Aug 21 14:20 ..`
`lrwxrwxrwx  1 pizzaman users        6 Aug 21 14:20 AppRun -> BitBox`
`-rw-r--r--  1 pizzaman users   159474 Aug 21 14:20 assets.rcc`
`-rwxr-xr-x  1 pizzaman users    51268 Aug 21 14:20 BitBox`
`-rw-r--r--  1 pizzaman users      155 Aug 21 14:20 bitbox.desktop`
`-rw-r--r--  1 pizzaman users        0 Aug 21 14:20 BitBox-x86_64.AppImage`
`-rw-r--r--  1 pizzaman users        0 Aug 21 14:20 default.png`
`lrwxrwxrwx  1 pizzaman users       11 Aug 21 14:20 .DirIcon -> default.png`
`drwx------ 58 pizzaman users     4096 Aug 21 14:20 doc`
`drwx------  2 pizzaman users     4096 Aug 21 14:20 lib`
`drwx------  2 pizzaman users     4096 Aug 21 14:20 libexec`
`-rw-r--r--  1 pizzaman users 11645848 Aug 21 14:20 libserver.so`
`drwx------  9 pizzaman users     4096 Aug 21 14:20 plugins`
`-rw-r--r--  1 pizzaman users      145 Aug 21 14:20 qt.conf`
`drwx------  2 pizzaman users     4096 Aug 21 14:20 resources`
`drwx------  3 pizzaman users     4096 Aug 21 14:20 translations`

The only image file is default.png with 0 bytes.

ref. https://wiki.archlinux.org/index.php/desktop_entries#Icons

**Comment by mercurytoxic** [comment]
The bitbox.desktop file contains no reference to the icon file except Icon=default this is not correct according to https://developer.gnome.org/desktop-entry-spec/

**Comment by benma** [comment]
@mercurytoxic thx. Can you open a PR? Icon: https://github.com/digitalbitbox/bitbox-wallet-app/tree/master/frontends/qt/resources/linux/usr/share/pixmaps

**Comment by mercurytoxic** [comment]
I see that in https://github.com/digitalbitbox/bitbox-wallet-app/blob/7c8cb2d4e08076ba701f7b5fe301d85fdb1c99d9/frontends/qt/Makefile#L39 the name of the icon is changed to **default** purposely, I assume this is because the .Appimage is self contained.

So from this I get that it would be up to the distribution maintainer of the package to add icon and sed the .desktop file with the proper icon name?
