### ISSUE TITLE
Better error message for insufficient funds / gas on ERC-20 transfer.

### ISSUE THREAD

**Issue by Egge21M** [digitalbitbox/bitbox-wallet-app#2604]
BitBox App gives an error when wallet does not have enough funds for ERC-20 gas. However the error message starts with "Ein unbekannter Fehler ist aufgetreten" which might be confusing for users. 
<img width="538" alt="Bildschirmfoto 2024-03-05 um 08 01 41" src="https://github.com/digitalbitbox/bitbox-wallet-app/assets/80262989/5a6a1804-5f6b-4df6-8385-e094c49c59da">

**Comment by benma** [comment]
@Beerosagos once made a fix for that:

https://github.com/digitalbitbox/bitbox-wallet-app/blob/0f7362d2c854f2971bd9ddb0af2956cf5d7214de/backend/coins/eth/etherscan/etherscan.go#L47

https://github.com/digitalbitbox/bitbox-wallet-app/blob/master/backend/coins/btc/handlers/handlers.go#L407-L410

@Beerosagos maybe it's cause the error string is checked for equality, but the EtherScan err msg has more stuff in it? Here we use `string.Contains` instead:

https://github.com/digitalbitbox/bitbox-wallet-app/blob/0f7362d2c854f2971bd9ddb0af2956cf5d7214de/backend/coins/eth/account.go#L575

**Comment by Beerosagos** [comment]
> Beerosagos once made a fix for that:

Yeah, it seems like etherscan error text is more detailed now and the strict comparison fails. Opened a PR to fix it: https://github.com/digitalbitbox/bitbox-wallet-app/pull/2607

**Comment by Beerosagos** [comment]
PR merged, closing
