### ISSUE TITLE
Feature Request: Generate new Seeds

### ISSUE THREAD

**Issue by on4r** [digitalbitbox/bitbox-wallet-app#2617]
Add an option to use the secure BitBox hardware randomness to (just) generate new seeds.

**Comment by benma** [comment]
You can generate a new seed by resetting your BitBox02 (check backup first!) and creating a new one.

Maybe related: generate BIP-85 child seeds from the BitBox02 seed: https://github.com/digitalbitbox/bitbox02-firmware/issues/556

**Comment by on4r** [comment]
Yes, that would work, but it's a little bit inconvenient, because I would have to restore my backup every time i generate a seed. I want to use the randomness of the BitBox to generate seeds for my friends. 
I'm thinking about a button in the app **Generate a 12/18/24 word seed**. 
Is the firmware capable of generating seeds without a reset? If so, it would be easy to implement.

**Comment by benma** [comment]
Look into BIP-85 (see link above), that seems like the it might be the right fit. BIP-85 is in the works and should be in one of the next releases.

Other than that, it is unlikely we would add a similar feature.

**Comment by on4r** [comment]
You are right @benma, BIP-85 as mentioned above would resolve my problem. 
Thanks for the reply! Closing.
