### ISSUE TITLE
Add new coin

### ISSUE THREAD

**Issue by dalijolijo** [digitalbitbox/bitbox-wallet-app#273]
I want to add Bitcore BTX support to Bitbox Hardware Wallet
Whit steps are needed?

**Comment by benma** [comment]
You'll need to fork this repo, and extend the code to add the coin, similar to how Litecoin is integrated.

See also this as an example of someone who integrated a coin: https://github.com/monaco-ex/bitbox-wallet-app/tree/pr-support-monacoin

Note that we likely won't be merging BTX into this repo, so you would have to maintain it in your fork.
