### ISSUE TITLE
GUI transaction list update issue

### ISSUE THREAD

**Issue by jonasschnelli** [digitalbitbox/bitbox-wallet-app#377]
When I switch between "Bitcoin Legacy" and "Bitcoin", I often get stuck in a view where the balance on top reflects the selected wallet "Bitcoin" when switching back from "Bitcoin legacy" but the transaction list is stuck with the last selection...

**Comment by benma** [comment]
https://github.com/digitalbitbox/bitbox-wallet-app/pull/406

@jonasschnelli Please test this PR.
