### ISSUE TITLE
Bitbox latest firmware 7.0.0 doesn't work at all with MyEtherWallet

### ISSUE THREAD

**Issue by baero** [digitalbitbox/bitbox-wallet-app#453]
The new firmware 7.0.0 has exacerbated the issues with MyEtherWallet. With the previous firmware it wasn't possible to send tokens, with the new one it doesn't even let you access the wallet. I tried with Chrome, Opera, Firefox with the same outcome. The only difference is that with Firefox the device blinks.

https://www.reddit.com/r/MyEtherWallet/comments/c4hb0u/can_somebody_from_mew_and_bitbox_provide_an/

**Comment by benma** [comment]
Apologies for the inconvenience caused. The team at MyEtherWallet has informed us that they will push a new release containing the fix very soon, probably today.

**Comment by benma** [comment]
MyEtherWallet released the fix yesterday, so the site and firmware 7.0.0 are compatible and should be working now. Thanks for your patience.
