### ISSUE TITLE
Inconsistent state after partial setup

### ISSUE THREAD

**Issue by jonathancross** [digitalbitbox/bitbox-wallet-app#482]
## Inconsistent state after partial setup

Platform: MacOS
Release: v4.11.0
Device: BitBox02

### Steps to reproduce

1. Start app
2. Plug in device
3. Name device
4. Click "Name Device & Continue"
5. Set passphrase
6. Click backup, but do not confirm on device. Read "I understand this backup is NOT password protected" (leading me to look for a way to skip)
7. In the app, click "Settings", and then back to "Manage device"

### Result

* Setup wizard is stuck back at "Create Wallet" Naming step.  "Name Device & Continue" button is disabled and does not become enabled when I add a name.
* Device continues to read "I understand this backup is NOT password protected", but cancel "X" will not cancel.  After several minutes, it seems it becomes responsive again and I can cancel.

After canceling on device, the  setup wizard stays stuck at "Create Wallet" screen asking for a device name and no way to continue.

My attempts to restart the app led to several other strange states as seen in screen shots below:

"Could not pair with app"
![bbox02_could_not_pair](https://user-images.githubusercontent.com/5115470/63057949-c13b6d00-beeb-11e9-8601-7ea89ad896bd.jpg)
"Unexpected error during restore: unlock failed."
![bbox02_unexpected_error](https://user-images.githubusercontent.com/5115470/63057951-c13b6d00-beeb-11e9-8b31-82a1e2999895.jpg)

### Log

[bbox02_log.txt](https://github.com/digitalbitbox/bitbox-wallet-app/files/3503443/bbox02_log.txt)

**Comment by benma** [comment]
Thanks for the report, we will look into it.

The second part of the issue is likely a duplicate of https://github.com/digitalbitbox/bitbox-wallet-app/issues/436 and relates to restarting the app while the device is performing a blocking action, like expecting user input.

**Comment by jonathancross** [comment]
This is bug quite old, I'm, assuming it has been fixed in the last 15 months :-)
