### ISSUE TITLE
AppImage won't run with glibc v2.30

### ISSUE THREAD

**Issue by x1ddos** [digitalbitbox/bitbox-wallet-app#484]
```
$ /x/BitBox-4.11.0-x86_64.AppImage
/x/BitBox-4.11.0-x86_64.AppImage: error while loading shared libraries:
 libserver.so: cannot dynamically load position-independent executable
```

The environment:

```
$ uname -a
Linux 4.19.66_1 #1 SMP PREEMPT Sun Aug 11 20:25:01 UTC 2019 x86_64 GNU/Linux

$ file /x/BitBox-4.11.0-x86_64.AppImage
/x/BitBox-4.11.0-x86_64.AppImage: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked,
 interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, stripped

$ sha256sum /x/BitBox-4.11.0-x86_64.AppImage
e87cbd2d595f9b04b5843afc74a721dc9e990346a184bb8eed754e73e266b67d  /x/BitBox-4.11.0-x86_64.AppImage
```

I haven't investigated yet but here's an [strace.txt](https://github.com/digitalbitbox/bitbox-wallet-app/files/3511974/strace.txt).

**Comment by x1ddos** [comment]
I extracted the appimage contents and indeed `libserver.so` seems to be PIE executable:

```
$ file -k libserver.so
libserver.so: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV)\012-  (Lepton 3.x), scale 59614-8705
, spot sensor temperature 0.000000, unit celsius, color scheme 8, calibration: offset 36893488147419103232
.000000, slope 0.000000, dynamically linked, interpreter /lib/ld64.so.1, Go BuildID=6Ku7YBG5KkaBpOK4vRqL/g
7EcnJclSLsnJ3_E_Q-F/tgpNOOXbyW6Z9npsK0C9/nAyFhzvG_NlXLeitoMC-, BuildID[sha1]=794652cdfa4e2c9662b2033748f30
62f88e042d3, stripped\012- data

$ readelf -l libserver.so | head -n 13

Elf file type is DYN (Shared object file)
Entry point 0x443450
There are 10 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040
                 0x0000000000000230 0x0000000000000230  R E    0x8
  INTERP         0x0000000000000270 0x0000000000000270 0x0000000000000270
                 0x000000000000000f 0x000000000000000f  R      0x1
      [Requesting program interpreter: /lib/ld64.so.1]
```

As of glibc v2.30 it will refuse `ldopen`-load a pic executable because:

> We cannot perform correct relocations for a second executable, and there is currently no way to run its ELF constructors (and it is unclear what the proper behavior would be anyway).
> 
> Therefore, we should refuse to load PIE objects using dlopen.

(from https://sourceware.org/bugzilla/show_bug.cgi?id=24323)

I indeed use glibc v2.30. In fact, I've tried running [v.4.4.0](https://github.com/digitalbitbox/bitbox-wallet-app/releases/tag/v4.4.0) from 14th of Jan wiith the same result. Is nobody running a more recent version of glibc?

Unless I'm completely off here, `libserver.so` needs to be built in a different way: of course relocatable but without PIE executable flag.

**Comment by x1ddos** [comment]
I suspect it'll also stop working on other distros when then upgrade to glibc 2.30. I've just checked and it seems the latest Ubuntu version is still at 2.29: https://packages.ubuntu.com/disco/libc6.

**Comment by x1ddos** [comment]
> libserver.so needs to be built in a different way

Or build it as `libserver.a` and link it into the final BitBox binary?

**Comment by x1ddos** [comment]
Just to confirm https://github.com/digitalbitbox/bitbox-wallet-app/issues/484#issuecomment-522257506 is indeed the issue I made a very quick change which removes `-pie` from go linker flags:

```patch
diff --git a/hardening.mk.inc b/hardening.mk.inc
index c8bbf36..e483e87 100644
--- a/hardening.mk.inc
+++ b/hardening.mk.inc
@@ -20,7 +20,7 @@ GOLNXSECFLAGS=${CFORTIFY} ${CSTACK}
 GODARWINSECFLAGS=${CFORTIFY} ${CSTACK}
 GOWINSECFLAGS=${CFORTIFY} ${CSTACK}
 
-GOLNXLDFLAGS=${LASLR} ${LRELRO},${LASLR},${LSTRIP},${LEXPORT},${LDEP}
-GOLNXEXTLDFLAGS=${LRELRO},${LASLR},${LSTRIP},${LEXPORT},${LDEP}
+GOLNXLDFLAGS=${LRELRO},${LSTRIP},${LEXPORT},${LDEP}
+GOLNXEXTLDFLAGS=${LRELRO},${LSTRIP},${LEXPORT},${LDEP}
 GODARWINLDFLAGS=${LASLR} -s -w
 GOWINLDFLAGS= -w -s ${GOWINEXTLDFLAGS} ${WLIBS} ${WEXPORT} ${WASLR} ${WDEP}
```

To be honest, very confusing hardening config. I thought it was supposed to be easy to understand and maintain to kind of... make the security better. :)
Ok, I then built libserver and replaced the original:

```
$ cd frontends/qt/server
$ make linux
....
$ file libserver.so
libserver.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, Go BuildID=oncJ5TMGfS7sYjklyA8j/qnyj_HhyzRBLKVjqNw9X/qZVb6bPihhfGTcFYGHr4/13PAM5hlz0ruiU2gU3lM, stripped

# /tmp/... is where I extracted appimage
$ mv libserver.so /tmp/x/squashfs-root/lib
$ cd /tmp/x/squashfs-root
# because I'm going to run the binary from the extracted appimage
# it needs to be pointed back to its bundled libraries manually
$ export LD_LIBRARY_PATH=$PWD/lib:/usr/lib
$ ./BitBox
```

This actually worked - it successfully loaded libserver.so - but raised another unrelated issue:

```
./BitBox: symbol lookup error: /usr/lib/libGL.so.1: undefined symbol: 
xcb_dri3_get_supported_modifiers
```

I highly suspect this is because the libxcb shared libs bundled with the appimage are outdated. There are lots of them: `ls lib/libxcb* | wc -l # outputs 17` and I don't even understand why they are bundled at all. Any sane person running Xorg or Wayland will surely have them available already. Otherwise you won't be running X.

In fact, removing them with `rm lib/libxcb*` to make `BitBox` binary pick up my system-wide versions made it finally work. This last issue with libxcb libs is beside the point. I'll save it for another bug. Just wanted to confirm pie executable was indeed the root cause.

**Comment by benma** [comment]
Thanks, great catch!

Indeed, removing the pie linker flag seems to be the way to go. I also ran [checksec.sh](https://drive.google.com/drive/u/1/folders/1T-0HJymanXgRP1rnf-Kq5C2u7l0Vh8oQ) afterwards to verify it still looks good.

For the libxcb issue: this might be fixed by https://github.com/probonopd/linuxdeployqt/issues/331. I upgraded linuxdeployqt. 

PR for both issues (unverified): https://github.com/digitalbitbox/bitbox-wallet-app/pull/488

Please check if building from this branch fixes your issues.
