### ISSUE TITLE
Switch from dep to go mod

### ISSUE THREAD

**Issue by x1ddos** [digitalbitbox/bitbox-wallet-app#485]
I've just converted the current master with a simple `go mod init` and rebuilt libserver without any issues concerning package dependencies.

What's holding you guys back?

If you try, make sure to `unset GOPATH` or `export GO111MODULE=on` and use a recent version of Go like 1.12.x.

**Comment by benma** [comment]
:+1: since it landed officially in Go, it was the logical next step. It was just a low priority since `dep` did not break yet ;) 

Since we have other Go projects as well, it is a good time to look into it again, so thanks for the reminder!

**Comment by benma** [comment]
Reminder: once we move to go mod, revert this commit:

https://github.com/digitalbitbox/bitbox-wallet-app/commit/9c6633ea73a69a9e28980f216d142c49128335f1

(`make android` went for 20min+ instead of like 1min, so I assume a compiler/toolchain bug).

**Comment by benma** [comment]
https://github.com/digitalbitbox/bitbox-wallet-app/pull/634

The above cannot be reverted as gomobile does not seem not to have caught up to the go mod development :O Can still build it after `go mod vendor` though, which seems workable for now.

**Comment by x1ddos** [comment]
Yeah, it seems Go modules still has many unsupported cases, unfortunately.

Anyway, good job in #634! Anything left to do or can this bug be closed now?

**Comment by benma** [comment]
Thanks. Can be closed :+1:

**Comment by x1ddos** [comment]
:package: :tada:
