### ISSUE TITLE
panic: noise: message is too short

### ISSUE THREAD

**Issue by x1ddos** [digitalbitbox/bitbox-wallet-app#486]
Not sure this was a one-off on my system but just in case.
Unfortunately, can't repro after firmware upgrade.

Started the BitBox appimage app and upgraded the firmware from 1.0.0 to 3.0.0 like it told me to. Device booted and right after entering my password, the app crashed with:

```
panic: noise: message is too short

goroutine 194 [running]:
github.com/digitalbitbox/bitbox-wallet-app/backend/devices/bitbox02.(*Device).pair(0xc0002760c0)
        /home/someuser/src/bitbox/bitbox-wallet-app/backend/devices/bitbox02/device.go:227 +0x11a8
github.com/digitalbitbox/bitbox-wallet-app/backend/devices/bitbox02.(*Device).init.func1(0xc0002760c0)
        /home/someuser/src/bitbox/bitbox-wallet-app/backend/devices/bitbox02/device.go:166 +0x200
created by github.com/digitalbitbox/bitbox-wallet-app/backend/devices/bitbox02.(*Device).init
        /home/someuser/src/bitbox/bitbox-wallet-app/backend/devices/bitbox02/device.go:158 +0x122
Received signal 6
#0 0x7f29f4d35fbf <unknown>
#1 0x7f29f3763645 <unknown>
#2 0x7f29f4d364ce <unknown>
#3 0x7f29f19a19b0 <unknown>
#4 0x7f29fa1b9541 <unknown>
  r8: 00007f29e907f7e0  r9: 0000000000000001 r10: 0000000000000008 r11: 0000000000000246
 r12: 0000000000000582 r13: 00007f29fb4a2380 r14: 0000000000000001 r15: 0000000000000000
  di: 0000000000000582  si: 0000000000000585  bp: 000000c000373280  bx: 000000c00005c700
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007f29fa1b9541  sp: 000000c000373268
  ip: 00007f29fa1b9541 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

Admittedly, I'm running an oob version of libserver.so because I can't run the appimage as is due to incompatibility with glibc v2.30 - more details on this in https://github.com/digitalbitbox/bitbox-wallet-app/issues/484 - so could be just my setup but still maybe worth checking out.

```
$ uname -a
Linux 4.19.66_1 #1 SMP PREEMPT Sun Aug 11 20:25:01 UTC 2019 x86_64 GNU/Linux

$ git br -v
* master 47fedb1 Merge branch 'release'
```

Althouh I didn't see anything interesting in the log file, attaching it anyway. 
[bitbox-noise-msg-too-short-panic.txt](https://github.com/digitalbitbox/bitbox-wallet-app/files/3513589/bitbox-noise-msg-too-short-panic.txt)

**Comment by benma** [comment]
Probably fixed by this https://github.com/digitalbitbox/bitbox02-firmware/pull/108 (verified only via Python lib, not app).

Please re-open it if you run into it again (after the next bb02 firmware upgrade to v4.0.0).
