### ISSUE TITLE
Unclear UI for mnemonic passphrase

### ISSUE THREAD

**Issue by x1ddos** [digitalbitbox/bitbox-wallet-app#487]
There is "Show BIP39 Mnemonic" button at the top in the Secrets section and another button at the bottom "Enable Mnemonic Passphrase" in the Expert Settings.

Is the bottom button related to "Show BIP39 Mnemonic" at the top? Why is one at the top in Secrets and the other one at the bottom in the Expert Settings? Unclear and no help text or description.

I suspect the botttom Expert Settings button will let me overwrite the current password with a mnemonic passphrase. Is it going to be BIP39? If I do enable it in the Expert Settings, what will the top "Show BIP39 Mnemonic" do then? Either way, I'd love some help text to confirm this instead of guessing.

![2019-08-19-000747_483x577_scrot](https://user-images.githubusercontent.com/25405/63230999-63719280-c215-11e9-9c46-80945e74edd9.png)

**Comment by benma** [comment]
Thanks for the report. We will add a sidebar guide to this page, similar to the BitBox01, which goes into some detail for every action/button.

In the meantime: the mnemonic passphrase is not to be confused with the "mnemonic" or "mnemonic seed". The passphrase option allows you to enter an additional passphrase, with every passphrase deriving a different wallet.

See also: https://en.bitcoin.it/wiki/Seed_phrase#Two-Factor_Seed_Phrases

**Comment by x1ddos** [comment]
Ah, 13th/25th word. Makes sense now.
Still, I think the wording is confusing. Maybe some users will even question how the password they enter on the device is connected to that BIP39 mnemonic button and the mnemonic passphrase at the bottom.

It feels like some alternative names from that bitcoin section would be less confusing. My personal favorite is Mnemonic Extension.

Unsure why "Enable Mnemonic Passpharse" is in the "Expert Settings". If explained correctly and in simple terms, I think it's quite a useful addition for every user.

**Comment by benma** [comment]
Agree that naming should be improved.

It is an expert setting because it requires great care when using it.

1) losing the passphrase means the funds are gone for good
2) the concept that every password derives a wallet is not very intuitive to newcomers, and leads to complications, e.g. a simple typo or mis-remembering the passphrase even slightly puts you in a different wallet with no warning. In the worst case, you might receive funds on it and not find it again.

**Comment by x1ddos** [comment]
> it requires great care when using it. losing the passphrase means the funds are gone for good

You could say the same thing about the backup or keys in general.

> the concept that every password derives a wallet is not very intuitive to newcomers

I would argue that the connection between the password a user enter on the device and "Show BIP39 mnemonic" button is also not very intuitiive to newcomers. I mean, the passphrase is not the only unintuitive thing that newcomers need to learn.

Anyway, as long it's described and explained, :+1:

**Comment by thisconnect** [comment]
Proposal: change `Show BIP39 Mnemonic` to `Show Mnemonic Seed` 

only mention BIP39 in the FAQ, as anyone who knows the BIP number would know what a Mnemonic Seed is anyways.

**Comment by thisconnect** [comment]
Proposal: change `Enable Mnemonic Passpharse` to `Enable Mnemonic Extension`

with the button in red to be extra careful here

**Comment by x1ddos** [comment]
I would even consider going as far as to say `Add Mnemonic Extension`.

**Comment by x1ddos** [comment]
Because "adding" is exactly what happens at the logical level. How it's implemented and whether that button "enables" something is a different story and I bet not every user will care about the implementation details.

**Comment by benma** [comment]
I'd probably skip the word `mnemonic` for the passphrase. The passphrase is usable even if the user does not look at or touch a mnemonic seed ever.

**Comment by benma** [comment]
>  would argue that the connection between the password a user enter on the device and "Show BIP39 mnemonic" button is also not very intuitiive to newcomers.

There is no connection? :sweat_smile: 

The `Show BIP39 mnemonic` button could also go to the expert mode though - it is an advanced use beyond sd card backup. I put it there first because it belongs with `Secrets`, but will reconsider.

**Comment by benma** [comment]
https://github.com/digitalbitbox/bitbox-wallet-app/pull/604 -> called `Mnemonic seed` and `Optional passphrase` now.

Leaving this issue open for a bit longer, as we should also include some helpful description in the guide.

**Comment by x1ddos** [comment]
@jstrnbrg would you like to take care of the guide here?

**Comment by x1ddos** [comment]
Also, related: https://github.com/digitalbitbox/bitbox-wallet-app/issues/487

**Comment by jstrnbrg** [comment]
@x1ddos yes :) Sorry I don't regularly check github notifications need to set up email reminders.

**Comment by benma** [comment]
Bump @jstrnbrg :P

**Comment by thisconnect** [comment]
Closing, as we just updated the information that is shown when enabling or disabling the passphrase prompt and currently have no plan to add a guide. As for "Show BIP39 Mnemonic" this was renamed to "Show recovery words", about a year ago in af412a6
 
> we should also include some helpful description in the guide.

Also related threre will be a design change to the passphrase.
