### ISSUE TITLE
bitbox-wallet not working with ElectrumX server 1.12

### ISSUE THREAD

**Issue by erols** [digitalbitbox/bitbox-wallet-app#499]
ElectrumX rejects connections from clients with version < 3.3.

Please see https://github.com/kyuupichan/electrumx/issues/842

BitBox Wallet is reporting version 0.0.1 so I can't connect it to my ElectrumX server. 

ElectrumX version 1.12

Logs from the server:

```
Aug 28 22:20:01 rocknode electrumx_server[23460]: INFO:ElectrumX:[72] SSL 192.168.178.33:33388, 0 total
Aug 28 22:20:10 rocknode electrumx_server[23460]: INFO:ElectrumX:[73] SSL 192.168.178.33:33396, 0 total
Aug 28 22:20:10 rocknode electrumx_server[23460]: INFO:ElectrumX:[73] attempting to crash old client with version 0.0.1
Aug 28 22:20:10 rocknode electrumx_server[23460]: INFO:ElectrumX:[73] changing task concurrency from 10 to 0
Aug 28 22:20:10 rocknode electrumx_server[23460]: INFO:ElectrumX:[73] disconnected whilst throttled
```

**Comment by erols** [comment]
Eventually the wallet times out when checking the connection
![Screenshot from 2019-08-28 22-34-19](https://user-images.githubusercontent.com/658656/63890867-5bfb7780-c9d3-11e9-91cf-0ffb604de2ba.png)

**Comment by benma** [comment]
Thanks for the report. We are aware of this issue and will resolve it in due time. (Another issue is that newer ElectrumX servers do not accept client protocol version 1.2 anymore :/).

In the meantime, you could use an older ElectrumX server version, or [Electrs](https://github.com/romanz/electrs).

**Comment by erols** [comment]
Ok. Do you know if I have to sync again if I use Electrs?

**Comment by benma** [comment]
I am afraid so.

**Comment by wilya7** [comment]
https://github.com/spesmilo/electrumx has forked the original kyuupichan/electrumx which dropped support for bitcoin

**Comment by benma** [comment]
The fix is merged and compatibility is restored in the next release, which is going to be published very soon. Thanks for your patience.

As @wilya7 mentioned, https://github.com/spesmilo/electrumx  is now the blessed fork of ElectrumX.

**Comment by x1ddos** [comment]
FTR https://github.com/digitalbitbox/bitbox-wallet-app/releases/tag/v4.24.1 is the release where the compatibility is restored.

**Comment by erols** [comment]
thanks. I will be building a bitbox-base soon and will be using it

**Comment by shesek** [comment]
Looks like [the docs](https://github.com/digitalbitbox/bitbox-wallet-app#electrum-server-backend) on the README needs to be updated, they still mention that "ElectrumX is currently not supported".

**Comment by benma** [comment]
> Looks like [the docs](https://github.com/digitalbitbox/bitbox-wallet-app#electrum-server-backend) on the README needs to be updated, they still mention that "ElectrumX is currently not supported".

Great catch, thanks. Fixed in https://github.com/digitalbitbox/bitbox-wallet-app/pull/1425/
