### ISSUE TITLE
Device attestation failed

### ISSUE THREAD

**Issue by thisconnect** [digitalbitbox/bitbox-wallet-app#572]
Steps to reprodcue:
1) start the app
2) plugin BB02
3) start typgin in password
4) close the app
5) reopen the app
6) Error:
Device attestation failed. Your BitBox may be counterfeit or compromised. Any coins on the BitBox02 may be at risk of being lost. Please contact support@shiftcrypto.ch immediately.

EDIT:
Sorry I just realize that it wasn't on firmware 4.1.0...
EDIT2: same with 4.1.0

**Comment by thisconnect** [comment]
I guess you can't / shouldn't close and reopen the app. In that case a comment like "If you close and reopen the app please disconnect and reconnect the BitBox" would probably be enough.

**Comment by benma** [comment]
Thanks! This is a known issue and unfortunately the "proper" fix for it will need some time to implement. Something similar would happen if you restart the app during address verification or any other operation which requires user interaction on the device.

Same issue (but different symptom): https://github.com/digitalbitbox/bitbox-wallet-app/issues/436

**Comment by benma** [comment]
Fixed in the latest release of the firmware (v8.0.0 in app 4.19.0) for this particular instance of the issue. This can still happen when the app is restarted during workflows other than the password entry, but over time we'll fix one by one.
