### ISSUE TITLE
Feature request: integration with electrum personal server

### ISSUE THREAD

**Issue by wilya7** [digitalbitbox/bitbox-wallet-app#589]
Hello, The app does not work at the present with "electrum Personal Server" [https://github.com/chris-belcher/electrum-personal-server](url)

Would the developers consider the integration or it is not something that can be put in the pipeline?

Thanks

**Comment by benma** [comment]
Did you try running EPS from master? There was an issue which is fixed in master, but not released yet.

See also: https://github.com/digitalbitbox/bitbox-wallet-app/issues/508#issuecomment-529214451

**Comment by wilya7** [comment]
Thank you. That worked! I should have checked the issue on EPS side. My apologies.
