### ISSUE TITLE
GUI blanks when switching desktops

### ISSUE THREAD

**Issue by hkjn** [digitalbitbox/bitbox-wallet-app#6]
# What should happen?

No blank GUI.

# What actually happened?

The BitBox-4.0.0-x86_64 app seems to show a blank qt window with no contents after switching desktops and returning  the one with the dbb app. See attached screenshot. ![dbb_blank](https://user-images.githubusercontent.com/287215/43723531-2aded2f8-9998-11e8-826a-944bc7dd03db.png)

I'm using cinnamon desktop environment, on Arch Linux.

Log entries continued appearing in `~/.config/bitbox/log.txt`, so the app appears to still function, apart from not redrawing itself.

When I resize the qt window, the rendering fixed itself and the GUI returned to normal. I can repro this by switching desktops away from the app and returning; the GUI goes blank every time.

**Comment by KasparEtter** [comment]
Thanks for reporting this! Do you have an idea how to solve this?

**Comment by hkjn** [comment]
@KasparEtter: No, I don't know how to fix this yet..

Presumably there's something that needs to happen when the Qt window receives focus again after switching desktops to redraw itself / the `WebEngineView`. Similar to how the `closeEvent` is overridden in the Qt frontend currently, maybe there is another event that fires when the window receives focus again?

* https://github.com/digitalbitbox/bitbox-wallet-app/blob/master/frontends/qt/main.cpp#L36

This seems like a list of all Qt events:

* http://doc.qt.io/archives/qt-4.8/qevent.html#static-public-members

Whatever is happening in the window resize event seems sufficient to redraw the `WebEngineView`.. so maybe that's a place to look.

**Comment by benma** [comment]
What does "switching desktop" mean?

**Comment by KasparEtter** [comment]
I assume dragging the windows to a different monitor.

**Comment by hkjn** [comment]
@benma @KasparEtter: With "switching desktop" I am referring to toggling between two separate virtual desktops, as is available in most Linux desktop environments. (I was planning to see if I could repro the issue in some standard environment like an Ubuntu or Tails LiveUSB, but haven't had time yet.. such a repro description could be more explicit about the steps taken to switch desktops..)

**Comment by benma** [comment]
Just checked on my xfce4. No issue with switching workspaces, or moving the app from one to another. Don't have a cinnamon env to check right now.

**Comment by benma** [comment]
I will close this due to age and inactivity. For what it's worth, I tried again and could not reproduce this issue.

Feel free to re-open it if it is still relevant.
