### ISSUE TITLE
Guide: Connect to your own node

### ISSUE THREAD

**Issue by thisconnect** [digitalbitbox/bitbox-wallet-app#617]
It would be great if the Guide for how to connect to your own node could be more detailed, see also the discussion in #615

With links to the blog post, required/supported software and products
- https://medium.com/shiftcrypto/regain-your-privacy-by-connecting-a-bitcoin-full-node-to-your-bitbox-wallet-58c96eb1f345
- https://github.com/romanz/electrs
- and BitBoxBase once it is available

One question is:
– Can I connect directly to Bitcoin Core?
 see also @benma answer https://github.com/digitalbitbox/bitbox-wallet-app/issues/615#issuecomment-546803423

**Comment by lausser** [comment]
Regarding BitBoxBase i can say, that you have to be patient until the Grafana dashboard says that the blockchain is 100% in sync and Electrum is up. Only then connecting the App to bitboxbase-ip:50002 will succeed.

**Comment by x1ddos** [comment]
@jstrnbrg would you like to take care of the guide?

**Comment by jstrnbrg** [comment]
@x1ddos sure, can do. In order to not duplicate content, what do you think of linking to this guide entry for instructions? https://guides.shiftcrypto.ch/bitboxapp/full-node/ @thisconnect we once talked about how to do that nicely, will ping you.

**Comment by x1ddos** [comment]
> what do you think of linking to this guide entry for instructions?

Looks nice but I don't really want to go into guide discussions. Maybe @Stadicus or @thisconnect.

**Comment by Stadicus** [comment]
I think we should have the most important info in the in-app guide (including what port to use), and then maybe a link to the external guide. At the moment, the external guide only describes the technicalities, some important information is missing.

Does not need to be long, just the essentials:

* Why should I run my own node?
* What options are there? 
* Should I use clearnet or Tor? 
* What is Tor and what port should I use (e.g. 9050 for daemon, 9150 for Tor browser proxy)

**Comment by jstrnbrg** [comment]
PR: https://github.com/digitalbitbox/bitbox-wallet-app/pull/925

**Comment by benma** [comment]
Wrong cc, you want @Stadicus I think ;)

**Comment by benma** [comment]
PR merged.
