### ISSUE TITLE
Android: can't seem to be able to upgrade firmware

### ISSUE THREAD

**Issue by x1ddos** [digitalbitbox/bitbox-wallet-app#656]
The screen shows upgrade button when when I tap on it, nothing happens.

![Screenshot_20191109-135031](https://user-images.githubusercontent.com/25405/68523899-8ca73980-02bf-11ea-973b-ffa24745f081.png)

Instead, I expected a confirmation dialog to pop up. It might be that it does pop up but somewhere outside of the phone screen.

**Comment by benma** [comment]
Worked for me with https://github.com/digitalbitbox/bitbox-wallet-app/pull/686
