### ISSUE TITLE
chrome crashes (webdev) on macos when opening qr scanner

### ISSUE THREAD

**Issue by thisconnect** [digitalbitbox/bitbox-wallet-app#676]
chrome crashes when clicking the QR scanner icon
$ git rev-parse HEAD
0b0efe6a74afbd648bceeaf671ec1dbf0987b47b

steps to reproduce 
- `make servewallet`
- `make webdev`
- open localhost:8080 in chrome
- goto Send
- click the QR icon
- confirm the dialog with "Allow" *
- crash!

![Screen Shot 2019-11-11 at 11 34 00 AM](https://user-images.githubusercontent.com/546900/68580731-40065e80-0477-11ea-9b94-5d5dcbcae837.png)

I just recently ugraded to macos 10.15.1 (19B88), but still using bash, not yet migrated to zsh  
(not sure if that is relevant at all).

The currently released App (4.14.1) works fine

If I build it mysef `make qt-osx`, clicking the qr icon then the whole screen gets stuck with a loading indicator

**Comment by thisconnect** [comment]
Firefox works fine btw :)

**Comment by thisconnect** [comment]
Tested without https://github.com/digitalbitbox/bitbox-wallet-app/commit/1eee074d3e26298d060b5a0bc883f8053ee74a87 and still got the crash.

**Comment by benma** [comment]
In the compiled macOS application, the scanner works fine for me.

**Comment by thisconnect** [comment]
QR Scanner works for me too tested BitBox-4.15.0-macOS.zip on macOS 10.15.1 (19B88) 👍 

About the Chrome on localhost/dev mode, could be that it doesn't like using the camera from http (Chrome wants to use the cam only on httpS afaik).

As to why my self built app crashed, I can't build at the moment, `./genassets.sh: line 21: rcc: command not found` but no time to look into that this week.

just close?

**Comment by benma** [comment]
Nice!

`rcc` is the Qt assets compiler, maybe you are missing the Qt installation on your system, or missing some of its tools, or it's not in PATH, etc.

> just close?

It's your issue :D keep it open if it is an issue for you and you want to track it, otherwise please close. I don't develop on macOS, so I won't be able to fix it though.
