### ISSUE TITLE
Network priority / fee dropdown doesn't appear

### ISSUE THREAD

**Issue by hkjn** [digitalbitbox/bitbox-wallet-app#7]
# What should happen?

Clicking "normal" in Network Priority when sending from "Legacy Bitcoin" view should show options for fee.

# What actually happened?

Focus flickers quickly from dropdown to entire qt window and back with no clear way to select fees, and the dropdown menu does not show up. (Pressing tab to switch focus to the dropdown followed by arrow down / up still allows cycling through options to lower fee, but this is probably not obvious to most users.)

Using BitBox-4.0.0-x86_64 on Arch Linux with cinnamon desktop environment.

See attached recording (ignore artifacts showing my desktop background, which seems to be due to the way the recording tool renders frames or something.. what appears visually is a quick shift in focus from the dropdown box to the entire qt window of the app and back again each time the box is clicked):
![feeflicker](https://user-images.githubusercontent.com/287215/43725957-2f3c5ee6-999e-11e8-8f3d-d43601858be9.gif)

**Comment by KasparEtter** [comment]
> Pressing tab to switch focus to the dropdown followed by arrow down / up still allows cycling through options to lower fee

but the behavior is different when using the mouse is definitely a bug. Quick shift in focus as well.

Does the dropdown never work with the cinnamon desktop environment (with which I'm not familiar at all)?

We only show different network priorities if they are actually different (which is typically the case for the Bitcoin mainnet and often not the case for the Bitcoin testnet). But if I understand you correctly, your issue is another one (probably related to your desktop environment).

**Comment by hkjn** [comment]
> Does the dropdown never work with the cinnamon desktop environment (with which I'm not familiar at all)?

This particular dropdown seems to never work, no.

> We only show different network priorities if they are actually different [...]

Yes, this was on Bitcoin mainnet, and since there were several options available when cycling focus and using arrow keys to switch between them I think there's some issue around how the dropdown is created, at least for my environment.

**Comment by hkjn** [comment]
I don't have a good explanation for _why_, but I tried to repro this issue today (still on `4.0.0`, still on same desktop environment) and now the drop-down shows up fine when clicking..

I'll close this since I can't repro, we can revisit in case others report the same.
