### ISSUE TITLE
Android BitBox01 not recognized

### ISSUE THREAD

**Issue by mercurytoxic** [digitalbitbox/bitbox-wallet-app#708]
https://github.com/digitalbitbox/bitbox-wallet-app/releases/tag/android-20191125
              
Plug in BitBox01, it blinks twice. Nothing happens.
![Screenshot_20191126-204112](https://user-images.githubusercontent.com/739809/69618062-6211fa80-108d-11ea-89be-10a848c3d3ea.jpg)

**Comment by benma** [comment]
Thanks.

As described in the [playstore listing](https://play.google.com/store/apps/details?id=ch.shiftcrypto.bitboxapp), the BitBox01 is not supported in the Android app:

> This is a very early Alpha version. It is intended as early-access for users who want to help testing and track the development.

> A BitBox02 hardware wallet is required.

One of the complications is that 2FA cannot be supported, as it would be insecure to have the 2FA app run on the same device.
