### ISSUE TITLE
configuration hash can't rely on json.Marshal

### ISSUE THREAD

**Issue by benma** [digitalbitbox/bitbox-wallet-app#715]
Discussed with @x1ddos 

https://github.com/digitalbitbox/bitbox-wallet-app/blob/master/backend/signing/configuration.go#L230-L233

`json.Marshal` is not guaranteed to create the same serialization always. The order of the keys could change, or whitespacing, or other things.

The Hash() should be replaced with a hand rolled hash accumulator over the fields.

Account database filenames depend on this hash, so the new impl. must either be compatible, or think about the consequence of creating new account databases (at the moment this merely means re-downloading the transactions, and get desktop notifications for the transactions again).

**Comment by x1ddos** [comment]
In addition to that, [RFC 4627](https://www.ietf.org/rfc/rfc4627.txt) explicitly defines JSON objects as unordered collections. It works today just because of an implementation detail of the specific package in use.

**Comment by x1ddos** [comment]
Resolved by #1267 and https://github.com/digitalbitbox/bitbox-wallet-app/pull/1314.
