### ISSUE TITLE
Missing New Version available

### ISSUE THREAD

**Issue by thisconnect** [digitalbitbox/bitbox-wallet-app#799]
App version: 4.17.1

![Screen Shot 2020-03-20 at 8 27 22 AM](https://user-images.githubusercontent.com/546900/77143893-ba2d9c00-6a84-11ea-952b-93c53f9b2ccd.png)

**Comment by Tomasvrba** [comment]
This is by design I believe as it is a patch version change only including firmware changes related to Electrum and Ethereum data fields. Correct me if I am wrong @benma

**Comment by benma** [comment]
To get the update notification for 6.1.0, you'll need [BitBoxApp 4.17.2](https://github.com/digitalbitbox/bitbox-wallet-app/releases/tag/v4.17.2). The app still bundles the firmware, so an old version of the app does not automatically fetch and display new firmware versions.

**Comment by benma** [comment]
> This is by design I believe as it is a patch version change only including firmware changes related to Electrum and Ethereum data fields. Correct me if I am wrong @benma

This would be about the app update notification, which we indeed skipped for 4.17.2 because of this.

**Comment by thisconnect** [comment]
👍
