### ISSUE TITLE
[naming things] Suggestion: rename `passphrase` to `BIP39 passphrase`

### ISSUE THREAD

**Issue by SCBuergel** [digitalbitbox/bitbox-wallet-app#801]
It is great that Bitbox2 supports mnemonics + passphrase. Unfortunately, not all providers are so clear about the distinction between password (for device) and BIP39 passphrase from which the HD seed is generated.

It would help users if you could be maximal explicit by renaming the `optional passphrase` under the `Expert settings` to `optional BIP39 passphrase` (and change in instructions and website accordingly).

**Comment by benma** [comment]
This also affects the `mnemonic seed`. A few months ago we renamed `BIP39 mnemonic` to `mnemonic seed`, and `mnemonic passphrase` to `optional passphrase`. The idea was that the term `BIP39` is very technical and meaningless to newcomers, so we opted to use more standard words.

Would it help if we added a entries to the blue guide on the right where BIP39 would be mentioned explicitly? So expert users coming from different HW vendors could look for it.

**Comment by My1** [comment]
> Would it help if we added a entries to the blue guide on the right where BIP39 would be mentioned explicitly?

that would help. espeially since outside of the bitbox the phrases used here arent that often used, so this can get chaotic fast when people using different wallets help each other.

**Comment by benma** [comment]
We've been using "optional passphrase" and "recovery words" for some years now and there does not seem to be any confusion among newcomers and users migrating from other wallets.
