### ISSUE TITLE
Add keybase URL for TOR/tails

### ISSUE THREAD

**Issue by SCBuergel** [digitalbitbox/bitbox-wallet-app#808]
On your release page you are nicely describing how to verify the signed releases by importing the signing pub keys from keybase. Since `curl` does not seem to work via TOR/tails but [keybase exposes their service as a hidden service](https://keybase.io/docs/command_line/tor) it might be worthwhile to also mention the command for importing signatures via TOR (only changing the first part of the keybase domain):

```
curl http://keybase5wmilwokqirssclfnsqrjdsi7jdir5wy7y7iu3tanwmtp6oid.onion/benma/pgp_keys.asc?fingerprint=2260e48288882c76afaa319d67a2b160f74db275 | gpg --import
```

**Comment by benma** [comment]
Nice addition, thanks. I added it to the GH release page (https://github.com/digitalbitbox/bitbox-wallet-app/releases/tag/v4.18.0) and we will port it to the user guides as well.

**Comment by real-or-random** [comment]
In both URLs in the release page, the `?` should be escaped or better the entire URL should be `'`-quoted because `?` is a special character in the shell.

**Comment by thisconnect** [comment]
Browser-Tor:
`curl --socks5-hostname localhost:9150 'http://keybase5wmilwokqirssclfnsqrjdsi7jdir5wy7y7iu3tanwmtp6oid.onion/benma/pgp_keys.asc?fingerprint=2260e48288882c76afaa319d67a2b160f74db275'`

Tor proxy:
`curl --socks5-hostname localhost:9050 'http://keybase5wmilwokqirssclfnsqrjdsi7jdir5wy7y7iu3tanwmtp6oid.onion/benma/pgp_keys.asc?fingerprint=2260e48288882c76afaa319d67a2b160f74db275'`

**Comment by benma** [comment]
Thanks @thisconnect 

@real-or-random I updated the v4.28.0 pre-release notes:

https://github.com/digitalbitbox/bitbox-wallet-app/releases/tag/v4.28.0

Looks good?

**Comment by benma** [comment]
@real-or-random out of curiosity, what shell are you using and what is the issue without the quotes? When I paste the previous line in my bash, without the single quotes, it works fine.

**Comment by real-or-random** [comment]
@real-or-random on (my) zsh:

```
> curl https://keybase.io/benma/pgp_keys.asc?fingerprint=2260e48288882c76afaa319d67a2b160f74db275
zsh: no matches found: https://keybase.io/benma/pgp_keys.asc?fingerprint=2260e48288882c76afaa319d67a2b160f74db275
```

It's trying to expand the parameter into filenames with that match the `?` pattern. To be honest, I have no idea why this is different from bash.
