### ISSUE TITLE
MacOS refuses to open bitcoin-wallet app v4.19.0 

### ISSUE THREAD

**Issue by wilya7** [digitalbitbox/bitbox-wallet-app#846]
I installed the app from the git repository and I checked the signature with gpg --verify 

After moving the app in the Application folders, when I try to open the app, MacOS Mojave 10.14.6
gives me this message error:

<img width="420" alt="Screenshot 2020-06-04 at 16 32 37" src="https://user-images.githubusercontent.com/1757313/83770692-a6f09c80-a681-11ea-9f78-f758945c9229.png">

My security setting after trying to open the app:
<img width="668" alt="Screenshot 2020-06-04 at 16 38 54" src="https://user-images.githubusercontent.com/1757313/83770909-f040ec00-a681-11ea-8e6a-193282d87e79.png">

Never had any problem with previous version of the app, therefore I reinstalled 4.18.0 and I get the usual notice that allows me to open the app.

**Comment by jstrnbrg** [comment]
Did you try right-clicking the icon and selecting "open"? (you might have to try twice)

**Comment by wilya7** [comment]
> Did you try right-clicking the icon and selecting "open"? (you might have to try twice)

No. I did not know about this. It worked. Thank you.
