### ISSUE TITLE
UI: Currency conversion doesn't work (CryptoCompare Rate Limit on VPN)

### ISSUE THREAD

**Issue by lclc** [digitalbitbox/bitbox-wallet-app#942]
I'm using a popular VPN service. So popular that others are also using it to access CryptoCompare (where BitBox has it's fiat exchange rate from) and run into the rate limit:

Response | "Error"
-- | --
Message | "You are over your rate limit please upgrade your account!"
HasWarning | false
Type | 99
RateLimit |  
calls_made |  
second | 1
minute | 5
hour | 99
day | 706
month | 95503
total_calls | 1204893
max_calls |  
second | 20
minute | 300
hour | 3000
day | 10000
month | 75000
Data | {}

Example effect in the UI:
![grafik](https://user-images.githubusercontent.com/1846033/89018229-cd4a5580-d31b-11ea-9c17-68e0ea4aad5d.png)

**Comment by x1ddos** [comment]
Once suggestion I have is to replace CryptoCompare with getting rates directly from an exchange or even multiple to let the users choose.

Here's one list of exchanges I found, sorted by their market share: https://data.bitcoinity.org/markets/exchanges/all/30d#rank_desc

**Comment by benma** [comment]
It would be nice to have one service to get all rates from, instead of having to call multiple different servers. Maybe not a big deal though.

We might want to show historical rates too at some point. Cryptocompare provides those afaik. Not sure if exchanges provide them as well.

**Comment by x1ddos** [comment]
One alternative maybe is just use something else instead of CryptoCompare? Like https://www.coingecko.com/en/api.

**Comment by lclc** [comment]
@x1ddos I'm sure all of them have rate-limiting.

This might be a rather exotic problem anyway.

**Comment by x1ddos** [comment]
Sure, everything is rate-limited. Yet, some would allow us to set up a
caching proxy to resolve this issue, others wouldn't. According to their
terms&conditions anyway. That is the difference I'm looking for.

**Comment by x1ddos** [comment]
We moved to another service in https://github.com/digitalbitbox/bitbox-wallet-app/pull/1196 which should resolve this issue. The change is expected to make into the next release planned later this month.

**Comment by thisconnect** [comment]
Got released 🎉   thanks @x1ddos and @benma  !
